/** Shared cs/en string table for the ProfitModule and its panels.
 *
 *  Lifted verbatim out of ProfitModule when the module was decomposed into panels
 *  (Round-8 finance direction): the composition root and every panel under
 *  `profit/` now import this one dict and call `useT(T)`, so the translations stay
 *  in a single place instead of drifting across colocated slices. cs/en unchanged. */
export const T = {
  cs: {
    days30: "30 dní",
    days90: "90 dní",
    months12: "12 měsíců",
    byChannels: "Podle kanálů",
    byProducts: "Podle produktů",
    resetMargins: "Obnovit výchozí marže",
    reportSyncActive: "Měsíční report počítá zisk z těchto hodnot (marže {m} · režie {o}/měs · {f}/obj.).",
    reportSyncInactive: "Použijte tuto marži a režii v měsíčním reportu, aby počítal skutečný zisk po nákladech.",
    liveData: "Živá data · Google Ads",
    sampleData: "Ukázková data",
    synced: "synchronizováno {date}",
    reconcileNote: "Blended marže v tomto modulu ({computed}) se liší o {delta} p.b. od marže v reportu ({persisted}) — stejný e-shop by ve dvou záložkách viděl jiný zisk. Sjednoťte je tlačítkem „{apply}“ výše.",
    applyToReport: "Použít v reportu",
    applyUpdate: "Aktualizovat report",
    applied: "Uloženo do reportu ✓",
    applying: "Ukládám…",
    applyFailed: "Uložení se nezdařilo.",
    realNumbersTitle: "Vaše reálná čísla (za zvolené období)",
    realNumbersDesc: "Zadejte skutečný obrat a útratu za reklamu za {period} — tabulka, souhrn i přerozdělení se přepočítají na vaši realitu (kanálový mix zůstává). Ne jen marže.",
    revenue: "Obrat",
    adSpend: "Útrata za reklamu",
    backToDemo: "Zpět na ukázku",
    recalculated: "Přepočítáno na vaše čísla. (Graf vývoje níže ukazuje tvar v čase.)",
    netAdProfit: "Čistý zisk z reklamy",
    grossProfitSub: "hrubý zisk {gross} − náklady {cost}",
    poasSub: "zisk na korunu reklamy · ROAS {roas}",
    blendedMargin: "Blended marže",
    weightedByRevenue: "vážená obratem",
    unprofitableChannels: "Ztrátové kanály",
    unprofitableAfterMargin: "prodělávají po marži",
    trendTitle: "Vývoj zisku a POAS v čase",
    netProfit: "Čistý zisk",
    poas: "POAS",
    lastPeriod: "poslední {granularity} {value}",
    unprofitableWarning_one: "kanál vypadá podle ROAS dobře, ale po započtení marže prodělává — jeho ROAS je pod bodem zvratu (1 / marže). Zvažte přesun rozpočtu do ziskových kanálů.",
    unprofitableWarning_other: "kanály/ů vypadají podle ROAS dobře, ale po započtení marže prodělávají — jejich ROAS je pod bodem zvratu (1 / marže). Zvažte přesun rozpočtu do ziskových kanálů.",
    colChannel: "Kanál",
    colRevenue: "Obrat",
    colCost: "Náklady",
    colRoas: "ROAS",
    colMargin: "Marže",
    colBreakeven: "Bod zvratu",
    colPoas: "POAS",
    colNetProfit: "Čistý zisk",
    marginAriaLabel: "Marže {channel}",
    legendProfitable: "Ziskový",
    legendProfitableDesc: "ROAS ≥ bod zvratu",
    legendUnprofitable: "Ztrátový",
    legendUnprofitableDesc: "ROAS pod bodem zvratu (1 / marže)",
    legendEditHint: "Marže upravte v tabulce — vše se přepočítá živě.",
    overheadTitle: "Zahrnout režijní náklady",
    overheadDesc: "Rozpočítá fixní režii podle obratu a odečte fulfillment na objednávku → skutečný příspěvkový POAS.",
    overheadInclude: "Zahrnout",
    overheadFixedMonthly: "Fixní režie / měsíc",
    overheadMonthsMult: "× {months} měsíce období",
    overheadPerOrder: "Náklad / objednávku",
    overheadFulfillmentHint: "fulfillment, balné, doprava",
    contributionPoas: "Příspěvkový POAS",
    rawPoas: "surový POAS {value}",
    colRawPoas: "Surový POAS",
    colOverhead: "Režie",
    colFulfillment: "Fulfillment",
    colContributionPoas: "Příspěvkový POAS",
    colAdjBreakeven: "Upravený bod zvratu",
    colContribution: "Příspěvek",
    overheadFooter: "Režie {overhead} + fulfillment {fulfillment} rozpočítáno · ztrátových po režii",
    scenarioDefaultName: "Scénář {n}",
    nextStepLabel: "Přesunout rozpočet",
    nextStepHintHelps: "Přerozdělení slibuje +{profit} zisku",
    nextStepHintOther: "Omezit ztrátové kanály v Kampaních",
    byWeeks: "po týdnech",
    byMonths: "po měsících",
    week: "týden",
    month: "měsíc",
    currencyUnit: "Kč",
  },
  en: {
    days30: "30 days",
    days90: "90 days",
    months12: "12 months",
    byChannels: "By channel",
    byProducts: "By product",
    resetMargins: "Reset margins",
    reportSyncActive: "The monthly report computes profit from these (margin {m} · overhead {o}/mo · {f}/order).",
    reportSyncInactive: "Use this margin & overhead in the monthly report so it computes true profit after costs.",
    liveData: "Live data · Google Ads",
    sampleData: "Sample data",
    synced: "synced {date}",
    reconcileNote: "This module's blended margin ({computed}) differs by {delta} pp from the report's margin ({persisted}) — the same store would read two different profits across two tabs. Unify them with the “{apply}” button above.",
    applyToReport: "Use in report",
    applyUpdate: "Update report",
    applied: "Saved to report ✓",
    applying: "Saving…",
    applyFailed: "Save failed.",
    realNumbersTitle: "Your actual numbers (for the selected period)",
    realNumbersDesc: "Enter your real revenue and ad spend for {period} — the table, summary and reallocation will recalculate against your books (channel mix is preserved). Not just margin.",
    revenue: "Revenue",
    adSpend: "Ad spend",
    backToDemo: "Back to demo",
    recalculated: "Recalculated against your numbers. (The trend chart below shows the shape over time.)",
    netAdProfit: "Net ad profit",
    grossProfitSub: "gross profit {gross} − cost {cost}",
    poasSub: "profit per unit of ad spend · ROAS {roas}",
    blendedMargin: "Blended margin",
    weightedByRevenue: "revenue-weighted",
    unprofitableChannels: "Unprofitable channels",
    unprofitableAfterMargin: "losing money after margin",
    trendTitle: "Profit and POAS trend over time",
    netProfit: "Net profit",
    poas: "POAS",
    lastPeriod: "last {granularity} {value}",
    unprofitableWarning_one: "channel looks fine on ROAS but loses money after margin — its ROAS is below break-even (1 / margin). Consider shifting budget to profitable channels.",
    unprofitableWarning_other: "channels look fine on ROAS but lose money after margin — their ROAS is below break-even (1 / margin). Consider shifting budget to profitable channels.",
    colChannel: "Channel",
    colRevenue: "Revenue",
    colCost: "Cost",
    colRoas: "ROAS",
    colMargin: "Margin",
    colBreakeven: "Break-even",
    colPoas: "POAS",
    colNetProfit: "Net profit",
    marginAriaLabel: "Margin for {channel}",
    legendProfitable: "Profitable",
    legendProfitableDesc: "ROAS ≥ break-even",
    legendUnprofitable: "Unprofitable",
    legendUnprofitableDesc: "ROAS below break-even (1 / margin)",
    legendEditHint: "Edit margins in the table — everything recalculates live.",
    overheadTitle: "Include overhead costs",
    overheadDesc: "Allocates fixed overhead by revenue share and deducts fulfillment per order → true contribution POAS.",
    overheadInclude: "Include",
    overheadFixedMonthly: "Fixed overhead / month",
    overheadMonthsMult: "× {months} months in the period",
    overheadPerOrder: "Cost / order",
    overheadFulfillmentHint: "fulfillment, packaging, shipping",
    contributionPoas: "Contribution POAS",
    rawPoas: "raw POAS {value}",
    colRawPoas: "Raw POAS",
    colOverhead: "Overhead",
    colFulfillment: "Fulfillment",
    colContributionPoas: "Contribution POAS",
    colAdjBreakeven: "Adjusted break-even",
    colContribution: "Contribution",
    overheadFooter: "Overhead {overhead} + fulfillment {fulfillment} allocated · unprofitable after overhead",
    scenarioDefaultName: "Scenario {n}",
    nextStepLabel: "Shift budget",
    nextStepHintHelps: "Reallocation projects +{profit} profit",
    nextStepHintOther: "Reduce unprofitable channels in Campaigns",
    byWeeks: "by week",
    byMonths: "by month",
    week: "week",
    month: "month",
    // "Kč", not "USD" — the overhead / per-order fields are koruny in BOTH
    // locales (there is no stored currency dimension) and render through fmtCZK.
    // Matches CostModelEditor and ProfitReallocationPanel; swept together on
    // 2026-08-06 because these two render into one screen.
    currencyUnit: "Kč",
  },
} as const;
