/** Shared contract between the AI route, the Gemini module and the client UI. */

export const PLATFORMS = ["google", "sklik"] as const;
export const TONES = ["vecny", "pratelsky", "premiovy", "akcni"] as const;

export type Platform = (typeof PLATFORMS)[number];
export type Tone = (typeof TONES)[number];

export const PLATFORM_LABELS: Record<Platform, string> = {
  google: "Google Ads (RSA)",
  sklik: "Sklik (Seznam)",
};

export const TONE_LABELS: Record<Tone, string> = {
  vecny: "Věcný a důvěryhodný",
  pratelsky: "Přátelský a lidský",
  premiovy: "Prémiový a kultivovaný",
  akcni: "Akční a motivující",
};

/** Google Ads character limits — enforced in the prompt and re-checked in the UI. */
export const AD_LIMITS = {
  headline: 30,
  description: 90,
  callout: 25,
  longHeadline: 90,
} as const;

export interface AdRequest {
  product: string;
  benefits: string;
  audience: string;
  platform: Platform;
  tone: Tone;
}

export interface AdResult {
  headlines: string[];
  descriptions: string[];
  callouts: string[];
  keywords: string[];
  longHeadline: string;
  rationale: string;
}

export interface AdResponse {
  result: AdResult;
  meta: {
    model: string;
    /** true when generated by the keyless fallback (no GEMINI_API_KEY) */
    demo: boolean;
    /** the exact prompt sent to the model — surfaced in the UI for transparency */
    prompt: string;
    tookMs: number;
  };
}

const str = (v: unknown): string => (typeof v === "string" ? v.trim() : "");

/** Validate + normalise an untrusted request body. */
export function validateAdRequest(
  input: unknown
): { valid: true; value: AdRequest } | { valid: false; error: string } {
  if (typeof input !== "object" || input === null) {
    return { valid: false, error: "Chybí data požadavku." };
  }
  const o = input as Record<string, unknown>;
  const product = str(o.product);
  const benefits = str(o.benefits);
  const audience = str(o.audience);
  const platform = o.platform as Platform;
  const tone = o.tone as Tone;

  if (product.length < 2 || product.length > 200) {
    return { valid: false, error: "Vyplňte název produktu nebo služby (2–200 znaků)." };
  }
  if (benefits.length < 2 || benefits.length > 600) {
    return { valid: false, error: "Vyplňte hlavní výhody (2–600 znaků)." };
  }
  if (audience.length < 2 || audience.length > 300) {
    return { valid: false, error: "Vyplňte cílovou skupinu (2–300 znaků)." };
  }
  if (!PLATFORMS.includes(platform)) {
    return { valid: false, error: "Neplatná platforma." };
  }
  if (!TONES.includes(tone)) {
    return { valid: false, error: "Neplatný tón komunikace." };
  }
  return { valid: true, value: { product, benefits, audience, platform, tone } };
}
