/** Shared contract between the AI route, the Gemini module and the client UI.
 *  Three tools, one envelope. Each tool maps to an Adamant service pillar:
 *    ads      → Výkonnostní reklama
 *    brief    → Tvorba obsahu
 *    analysis → Analýzy a strategie
 */

import type { CampaignPeriod } from "./campaigns/types";
import type { Block, FaqItem } from "./article";
import type { KeywordIntent } from "./keywords/types";
import type { OrganicChannel } from "./organic-channels/types";
import type { SupportedLocale } from "./format";

export type AiMode =
  | "ads"
  | "brief"
  | "analysis"
  | "twin-reply"
  | "twin-style"
  | "repurpose"
  | "local-review-reply"
  | "article-draft"
  | "cohort-diagnosis"
  | "keyword-clusters"
  | "comparison-outline"
  | "lp-variant-ideas"
  | "lead-source-diagnosis"
  | "channel-research"
  | "onboarding-scan";
export const AI_MODES: AiMode[] = [
  "ads",
  "brief",
  "analysis",
  "twin-reply",
  "twin-style",
  "repurpose",
  "local-review-reply",
  "article-draft",
  "cohort-diagnosis",
  "keyword-clusters",
  "comparison-outline",
  "lp-variant-ideas",
  "lead-source-diagnosis",
  "channel-research",
  "onboarding-scan",
];

export interface AiMeta {
  model: string;
  /** true when generated by the deterministic fallback (no provider available:
   *  no Claude CLI in dev / no GEMINI_API_KEY in prod) */
  demo: boolean;
  /** the exact prompt sent to the model — surfaced in the UI for transparency */
  prompt: string;
  tookMs: number;
  /** model tag of the provider that actually served the result */
  provider?: string;
  /** total provider attempts, including retries and any self-repair re-prompt */
  attempts?: number;
  /** true when the environment-preferred provider failed and another provider
   *  (or the deterministic demo) served the result instead */
  fellBack?: boolean;
  /** true when the output was re-prompted once to correct limit violations */
  repaired?: boolean;
  /** limit violations detected in the first model output (before repair/clamp) */
  violations?: string[];
  /** token usage when the provider reports it (Gemini); absent for the Claude
   *  subscription path */
  usage?: { inputTokens: number; outputTokens: number; totalTokens: number };
  /** estimated USD cost of the call; 0 for the dev Claude subscription path */
  estCostUsd?: number;
}

/** Typed error envelope for the AI routes. Success responses are AiResponse<T>;
 *  every failure should serialize as an AiError so clients branch on `code` rather
 *  than parsing a free-text message. Status → code:
 *    400/422 → "invalid"      (bad request / failed validation)
 *    413     → "too_large"    (body over the size cap)
 *    429     → "rate_limited" (per-IP min/day) or "quota" (signed-in plan limit)
 *    502     → "failed"       (provider / generation error)
 *    400/401/429 → "provider" (BYOM: the caller's OWN key/account/model failed —
 *                              surfaced so they can fix it, never retried on the
 *                              app's provider; the message carries the specifics)
 *  `retryAfter` accompanies "rate_limited"; `upgradeUrl` accompanies "quota". */
export type AiErrorCode = "invalid" | "rate_limited" | "quota" | "too_large" | "failed" | "provider";
export interface AiError {
  code: AiErrorCode;
  /** human, localized (cs-CZ) message. Named `error` (not `message`) to match the
   *  field the routes already emit and clients already read (`json.error`), so the
   *  envelope is additive — existing handling keeps working, new clients read `code`. */
  error: string;
  /** seconds until retry — present for code "rate_limited" */
  retryAfter?: number;
  /** upgrade path — present for code "quota" */
  upgradeUrl?: string;
}

export interface AiResponse<T> {
  result: T;
  meta: AiMeta;
}

// ===========================================================================
// Tool 1 — PPC ads
// ===========================================================================

export const PLATFORMS = ["google", "sklik"] as const;
export const TONES = ["vecny", "pratelsky", "premiovy", "akcni"] as const;

export type Platform = (typeof PLATFORMS)[number];
export type Tone = (typeof TONES)[number];

export const PLATFORM_LABELS: Record<Platform, string> = {
  google: "Google Ads (RSA)",
  sklik: "Sklik (Seznam)",
};

export const TONE_LABELS: Record<Tone, string> = {
  vecny: "Věcný a důvěryhodný",
  pratelsky: "Přátelský a lidský",
  premiovy: "Prémiový a kultivovaný",
  akcni: "Akční a motivující",
};

/** Google Ads character limits — enforced in the prompt and re-checked in the UI. */
export const AD_LIMITS = {
  headline: 30,
  description: 90,
  callout: 25,
  longHeadline: 90,
} as const;

export interface AdRequest {
  product: string;
  benefits: string;
  audience: string;
  platform: Platform;
  tone: Tone;
  /** optional free-text refinement note from a re-run („kratší", „vynech ceny") —
   *  appended to the user prompt only and naturally busts the input-hash cache */
  refine?: string;
}

export interface AdResult {
  headlines: string[];
  descriptions: string[];
  callouts: string[];
  keywords: string[];
  longHeadline: string;
  rationale: string;
}

export type AdResponse = AiResponse<AdResult>;

// ===========================================================================
// Tool 2 — SEO content brief
// ===========================================================================

export const CONTENT_TYPES = ["blog", "kategorie", "produkt"] as const;
export type ContentType = (typeof CONTENT_TYPES)[number];

export const CONTENT_TYPE_LABELS: Record<ContentType, string> = {
  blog: "Blogový článek",
  kategorie: "Kategorie e-shopu",
  produkt: "Produktová stránka",
};

/** SEO best-practice limits — checked in the UI like the ad limits. */
export const SEO_LIMITS = {
  titleTag: 60,
  metaDescription: 155,
} as const;

/** Real keyword metrics (from the Keyword Planner tool) used to ground the brief
 *  in actual demand instead of model invention. Optional. */
export interface BriefKeyword {
  keyword: string;
  volume: number;
  competition: string;
}

export interface BriefRequest {
  topic: string;
  primaryKeyword: string;
  audience: string;
  contentType: ContentType;
  /** optional real keyword data carried over from the keyword-research tool */
  keywords?: BriefKeyword[];
  /** the calling project's id (injected by useAiTool) — used server-side to derive
   *  the brand grounding below; never trusted for tenancy on its own */
  projectId?: string;
  /** server-derived brand grounding (what the project sells + how it talks). Injected
   *  into the USER prompt only — like `refine` — so the system prompt + schema stay
   *  byte-identical and the LLM-gate golden holds. Grounds the draft in the real
   *  product instead of a generic keyword piece. */
  brand?: string;
  /** optional free-text refinement note from a re-run („kratší", „vynech ceny") —
   *  appended to the user prompt only and naturally busts the input-hash cache */
  refine?: string;
}

export interface BriefResult {
  titleTag: string;
  metaDescription: string;
  h1: string;
  slug: string;
  outline: { heading: string; points: string[] }[];
  faq: { question: string; answer: string }[];
  keywords: string[];
  internalLinks: string[];
  rationale: string;
}


// ===========================================================================
// Tool 3 — performance analysis (grounded in the dashboard dataset)
// ===========================================================================

export const ANALYSIS_PERIODS = ["30d", "90d", "12m"] as const;
export type AnalysisPeriod = (typeof ANALYSIS_PERIODS)[number];

export const ANALYSIS_PERIOD_LABELS: Record<AnalysisPeriod, string> = {
  "30d": "30 dní",
  "90d": "90 dní",
  "12m": "12 měsíců",
};

export const ANALYSIS_PERIOD_LABELS_EN: Record<AnalysisPeriod, string> = {
  "30d": "30 days",
  "90d": "90 days",
  "12m": "12 months",
};

export function analysisPeriodLabel(p: AnalysisPeriod, locale: SupportedLocale): string {
  return (locale === "en" ? ANALYSIS_PERIOD_LABELS_EN : ANALYSIS_PERIOD_LABELS)[p];
}

export interface AnalysisRequest {
  period: AnalysisPeriod;
  /** optional free-text refinement note from a re-run („kratší", „vynech ceny") —
   *  appended to the user prompt only and naturally busts the input-hash cache */
  refine?: string;
}

export interface AnalysisResult {
  headline: string;
  summary: string;
  wins: string[];
  risks: string[];
  actions: { title: string; detail: string }[];
}


// ===========================================================================
// Tool 14 — monthly recap (per-project, per-business-type grounded)
// ===========================================================================
// Like `analysis` but grounded on the caller's OWN project dataset and framed to
// the project's business type, so the recap fits non-eshop projects (local /
// leadgen / content) instead of always speaking e-commerce (revenue/PNO/ROAS).
// Field names are metric-neutral (highlights/watchouts/priorities) for the same
// reason. Reuses AnalysisPeriod.

export interface MonthlyRecapRequest {
  period: AnalysisPeriod;
  /** the project to ground on; resolved + tenancy-checked by the route, which
   *  rewrites it to the EFFECTIVE grounding id before it reaches the cache key */
  projectId?: string;
  /** optional free-text refinement note from a re-run — appended to the user
   *  prompt only, so the system+schema fingerprint (gate/golden) stays stable */
  refine?: string;
}

export interface MonthlyRecapResult {
  headline: string;
  summary: string;
  highlights: string[];
  watchouts: string[];
  priorities: { title: string; detail: string }[];
}


// ---------------------------------------------------------------------------
// Report chat — a follow-up conversation grounded in the same performance
// snapshot as the analysis. The opening report is the deterministic analysis;
// each turn here asks the model a free-text question about those numbers.
// ---------------------------------------------------------------------------

export interface ChatTurn {
  role: "user" | "assistant";
  content: string;
}

export interface ChatRequest {
  period: AnalysisPeriod;
  /** conversation so far, oldest first, ending with the latest user turn */
  messages: ChatTurn[];
  /** Phase-D: which project to ground on. The route resolves it to a dataset
   *  (demo project or the caller's owned project) and falls back to the base
   *  case-study when absent / unresolved. */
  projectId?: string;
}

export interface ChatResult {
  reply: string;
}


// ===========================================================================
// Tool 4 — campaign / portfolio evaluation (grounded in synced Google Ads data)
// ===========================================================================

export const EVAL_SCOPES = ["campaign", "overall"] as const;
export type EvalScope = (typeof EVAL_SCOPES)[number];

export type EvalPriority = "high" | "medium" | "low";
export const EVAL_PRIORITIES: EvalPriority[] = ["high", "medium", "low"];

export const EVAL_PRIORITY_LABELS: Record<EvalPriority, string> = {
  high: "Vysoká priorita",
  medium: "Střední priorita",
  low: "Nízká priorita",
};

export const EVAL_PRIORITY_LABELS_EN: Record<EvalPriority, string> = {
  high: "High priority",
  medium: "Medium priority",
  low: "Low priority",
};

export function evalPriorityLabel(p: EvalPriority, locale: SupportedLocale): string {
  return (locale === "en" ? EVAL_PRIORITY_LABELS_EN : EVAL_PRIORITY_LABELS)[p];
}

export interface EvalRecommendation {
  title: string;
  detail: string;
  priority: EvalPriority;
}

export interface CampaignReportResult {
  /** one-line verdict */
  verdict: string;
  /** health score 0–100 */
  score: number;
  /** one short paragraph */
  summary: string;
  strengths: string[];
  weaknesses: string[];
  /** prioritised next steps */
  recommendations: EvalRecommendation[];
}


/** A stored, persisted evaluation — the shape the API returns and the client
 *  renders. Independent of the SQLite layer so the client never imports server
 *  code. */
export interface CampaignReport {
  scope: EvalScope;
  /** null for the overall / portfolio report */
  campaignId: string | null;
  period: string;
  result: CampaignReportResult;
  meta: AiMeta;
  /** ISO timestamp when the report was generated */
  createdAt: string;
}

/** A lightweight point in a campaign's (or the portfolio's) score history — one
 *  per stored evaluation, ordered oldest → newest. Carries only what the trend
 *  timeline needs so the full report payloads never travel over the wire. */
export interface ReportHistoryPoint {
  /** health score 0–100 at that evaluation */
  score: number;
  /** the one-line verdict, surfaced in the point's tooltip */
  verdict: string;
  /** the data window the evaluation used ("7d" | "30d" | "90d") */
  period: string;
  /** true when produced by the keyless demo fallback */
  demo: boolean;
  /** ISO timestamp when the report was generated */
  createdAt: string;
}

export interface EvaluationRequest {
  scope: EvalScope;
  /** required when scope === "campaign" */
  campaignId?: string;
  period: CampaignPeriod;
}

// ===========================================================================
// Tool 5 — speed-to-lead reply (on-brand AI reply for the Rychlá reakce inbox)
// ===========================================================================

/** How an enquiry physically arrived — mirrors LeadChannel in lib/speed-lead/sample
 *  without importing client-adjacent sample data. This is a SUB-kind of the twin's
 *  `leads` channel: it changes the phrasing (a missed call earns a callback offer,
 *  a form earns a written answer) but not the voice. */
export const LEAD_CHANNELS = ["form", "call", "email", "chat"] as const;
export type LeadArrivalChannel = (typeof LEAD_CHANNELS)[number];

/** The trained voice, flattened for the wire. Mirrors `TwinVoice` in lib/twin/types
 *  minus the storage bookkeeping — `always`/`never` are the two halves of that
 *  type's `constraints` list, split so the request validates without object parsing. */
export interface TwinReplyVoice {
  /** the style guide, injected verbatim into the user prompt */
  directives?: string;
  traits?: string[];
  lengthHint?: string;
  /** hard rules the reply must obey */
  always?: string[];
  /** hard rules the reply must never break */
  never?: string[];
}

/** One past turn of the conversation, oldest first. */
export interface TwinReplyTurn {
  direction: "in" | "out";
  content: string;
}

export interface TwinReplyRequest {
  /** the message we're replying to */
  inbound: string;
  /** the twin channel this reply goes out on (leads | email | chat | social | …) */
  channel: string;
  /** for `leads`, how the enquiry arrived (form | call | email | chat) */
  arrival?: string;
  /** the project / service type, used to keep the reply on-brand */
  projectType: string;
  /** who we're writing to, for a personal greeting */
  contact?: string;
  /** the voice trained for this channel (falls back to the generic register) */
  voice?: TwinReplyVoice;
  /** the last few turns with this contact, oldest first */
  thread?: TwinReplyTurn[];
  /** real messages in the brand's voice, for the model to imitate */
  examples?: string[];
  /** directives distilled from drafts a human REJECTED — the feedback loop that
   *  stops the twin repeating a mistake it has already been corrected on */
  avoid?: string[];
  /** captured BANT qualification (Czech summary of the known fields) so a lead reply
   *  doesn't re-ask what's already known and matches the lead's disposition */
  qualification?: string;
  /** the business / brand name. The route upgrades this to the full derived brand
   *  context (what they sell + how they talk) when a projectId is present, so the
   *  reply speaks the business's real offering — injected into the USER prompt only,
   *  so the golden (system + schema) holds. */
  brand?: string;
  /** the caller's project, so the route can ground the reply in its catalog/brand */
  projectId?: string;
  /** optional free-text refinement note from a re-run („kratší", „vynech ceny") —
   *  appended to the user prompt only and naturally busts the input-hash cache */
  refine?: string;
}

export interface TwinReplyResult {
  /** the full, ready-to-send reply */
  reply: string;
  /** follow-up questions that move the conversation forward (lead qualification) */
  questions: string[];
  /** the model's own 0–100 read of how send-ready this is. Drives the autonomy
   *  gate: under `auto`, a draft self-approves only above the channel's threshold. */
  confidence: number;
  /** anything a human should check before sending (a promise, a price, a claim the
   *  grounding doesn't support). A non-empty list always forces human review. */
  risks: string[];
  /** one line on how the voice was applied — shown in the outbox, not sent */
  toneNotes: string;
}


// ===========================================================================
// Tool 17 — twin style training (Twin: from REAL past messages the brand has
// sent, plus the brand's answers to the twin's own follow-up questions, distil a
// reusable per-channel VOICE: the style directives, the traits, a length hint,
// the always/never guardrails and a few exemplar lines. The model also returns
// what it still cannot tell — `gapQuestions` — which the user answers to feed
// the next distillation. That question→answer→re-distil cycle IS the training
// loop; there is no separate interview operation.)
// ===========================================================================

/** One answered training question, fed back into the next distillation. */
export interface TwinStyleAnswer {
  question: string;
  answer: string;
}

/** A distilled always/never rule. */
export interface TwinStyleConstraint {
  kind: "do" | "dont";
  rule: string;
}

export interface TwinStyleRequest {
  /** the tone scope being trained: `generic` or one twin channel */
  scope: string;
  /** the project / service type */
  projectType: string;
  /** real past messages written in this brand's voice — the primary evidence */
  samples?: string[];
  /** the brand's answers to questions the twin asked in an earlier pass */
  answers?: TwinStyleAnswer[];
  /** the directives already in place, when refining rather than starting cold */
  current?: string;
  /** the brand name; upgraded to the derived brand context by the route */
  brand?: string;
  /** the caller's project, so the route can ground the voice in its catalog */
  projectId?: string;
  /** optional free-text refinement note from a re-run */
  refine?: string;
}

export interface TwinStyleResult {
  /** one line on what characterises this voice */
  summary: string;
  /** the style guide, second person, injected verbatim into every draft prompt */
  directives: string;
  /** short adjectives describing the register */
  traits: string[];
  /** e.g. "2–4 věty" */
  lengthHint: string;
  /** the always/never rules the samples imply */
  constraints: TwinStyleConstraint[];
  /** exemplar lines in this voice, for few-shot imitation at draft time */
  examples: string[];
  /** what the model still cannot tell about the voice — the next training round */
  gapQuestions: string[];
}


// ===========================================================================
// Tool 6 — content repurposing (Distribuce: one article → channel-native variants)
// ===========================================================================

export interface RepurposeRequest {
  /** the source article title */
  title: string;
  /** the source article URL (the variants link back to it, UTM-stamped client-side) */
  url: string;
  /** optional article body / excerpt to ground the variants in the real content */
  body?: string;
  /** channel labels to write a variant for (e.g. „LinkedIn", „Instagram") */
  channels: string[];
  /** tone of voice, shared with the other tools */
  tone: Tone;
  /** the caller's project, so the route can resolve its trained twin voice */
  projectId?: string;
  /** the twin's trained voice for this channel. Resolved SERVER-SIDE from the
   *  project's twin (lib/twin/load) and injected into the USER prompt only, so the
   *  golden holds — never accepted from the client, which could otherwise put words
   *  in another tenant's mouth. Absent for an untrained twin. */
  voice?: TwinReplyVoice;
  /** optional free-text refinement note from a re-run („kratší", „vynech ceny") —
   *  appended to the user prompt only and naturally busts the input-hash cache */
  refine?: string;
}

/** One channel-native variant: the channel label and its ready-to-ship text. */
export interface RepurposeVariant {
  channel: string;
  text: string;
}

export interface RepurposeResult {
  /** one variant per requested channel */
  variants: RepurposeVariant[];
}


// ===========================================================================
// Tool 7 — local review reply (Lokální dominance: draft a public reply to a
// Google Business review — warm thanks for high ratings, empathetic
// de-escalation + an offline contact offer for low ratings)
// ===========================================================================

export interface LocalReviewReplyRequest {
  /** the public review text we're replying to */
  reviewText: string;
  /** the star rating left by the reviewer (1–5) — drives the tone */
  rating: number;
  /** the locality the review belongs to, for a place-aware reply */
  area: string;
  /** optional business type, to keep the reply on-brand */
  businessType?: string;
  /** the business name, so the reply can reference / sign off as the business
   *  instead of a generic "we" */
  businessName?: string;
  /** optional free-text refinement note from a re-run („kratší", „vynech ceny") —
   *  appended to the user prompt only and naturally busts the input-hash cache */
  refine?: string;
}

export interface LocalReviewReplyResult {
  /** the full, ready-to-publish public reply to the review */
  reply: string;
}


// ===========================================================================
// Tool 8 — article draft (Obsah & SEO: rozepíše hotový brief do plnohodnotného
// konceptu článku jako typovaný Block[] + FAQ, který se vykreslí stejným
// rendererem jako publikovaný článek na /clanek)
// ===========================================================================

/** The approved brief carried into the draft step — a subset of BriefResult that
 *  grounds the article, plus the optional content type for tone/structure. */
export interface ArticleDraftRequest {
  /** SEO title tag — also the working article title */
  titleTag: string;
  /** meta description — seeds the perex / lead paragraph */
  metaDescription: string;
  /** H1 heading — the article's display title */
  h1: string;
  /** URL slug, carried through for export filenames */
  slug: string;
  /** the approved H2 outline (heading + bullet points) the article follows */
  outline: { heading: string; points: string[] }[];
  /** the approved FAQ (question + answer) re-rendered as the article's FAQ */
  faq: { question: string; answer: string }[];
  /** related keywords to weave in naturally (no stuffing) */
  keywords: string[];
  /** target audience, when known, to set the tone */
  audience?: string;
  /** content type (blog / category / product), when known */
  contentType?: ContentType;
  /** the calling project's id (injected by useAiTool) — used server-side to derive
   *  the brand grounding below */
  projectId?: string;
  /** server-derived brand grounding (what the project sells + how it talks). Injected
   *  into the USER prompt only — like `refine` — so system + schema stay byte-identical
   *  and the LLM-gate golden holds. Keeps the article on-brand, not generic. */
  brand?: string;
  /** optional free-text refinement note from a re-run („kratší", „vynech ceny") —
   *  appended to the user prompt only and naturally busts the input-hash cache */
  refine?: string;
}

/** A near-publishable article draft in the app's headless content model — the
 *  exact shape ArticleBody renders. blocks is the typed body, faq the FAQ list. */
export interface ArticleDraftResult {
  /** the article body as the typed Block union (paragraphs, H2/H3, lists,
   *  callout, CTA) — renders through the same ArticleBody as /clanek */
  blocks: Block[];
  /** the FAQ, as the renderer's FaqItem shape (question + inline answer) */
  faq: FaqItem[];
}


// ===========================================================================
// Tool 9 — cohort diagnosis (CAC → LTV: an AI read of the computed cohort
// economics — names the problem cohort and the single lever to pull first.
// Grounded strictly in the numbers the module already computed; the model
// invents no figures.)
// ===========================================================================

/** One cohort's economics, flattened to the few numbers the diagnosis needs.
 *  A serializable projection of CohortMetrics (lib/ltv/compute) so the client
 *  never ships the full curve/channel graph to the model. */
export interface CohortDiagnosisCohort {
  /** the cohort month label (e.g. „2025-01") — also the worstCohort identifier */
  month: string;
  /** acquisition cost per signup (CZK) */
  cac: number;
  /** lifetime value per user (CZK) */
  ltv: number;
  /** LTV : CAC ratio */
  ltvCac: number;
  /** 1-based payback month, or null when not recovered within the horizon */
  paybackMonth: number | null;
  /** M3 retention as a fraction (0–1) */
  m3: number;
  /** signups in the cohort */
  signups: number;
}

/** Blended portfolio summary + optional trend direction handed to the model. */
export interface CohortDiagnosisRequest {
  /** the per-cohort rows, chronological (oldest first) — REAL numbers only */
  cohorts: CohortDiagnosisCohort[];
  /** blended CAC across all cohorts (CZK) */
  blendedCac: number;
  /** average LTV : CAC across cohorts */
  avgLtvCac: number;
  /** average payback month across cohorts, or null */
  avgPayback: number | null;
  /** the cohort trend direction, when there are ≥ 2 cohorts */
  trend?: TrendDirection;
  /** e-shop project → customer / repeat-purchase framing instead of signups / ARPU */
  eshop?: boolean;
  /** optional free-text refinement note from a re-run („kratší", „vynech ceny") —
   *  appended to the user prompt only and naturally busts the input-hash cache */
  refine?: string;
}

/** The trend direction shape, mirrored from lib/ltv/compute so the client+server
 *  contract stays free of server (compute) imports. */
export type TrendDirection = "improving" | "worsening" | "flat";

export interface CohortDiagnosisResult {
  /** one short paragraph reading the unit economics */
  summary: string;
  /** the month label of the weakest cohort (must be one of the supplied labels) */
  worstCohort: string;
  /** the single most impactful lever to pull first, as a concrete action */
  recommendation: string;
  /** optional 1–3 risks to watch */
  risks?: string[];
}


// ===========================================================================
// Tool 10 — keyword intent-clustering (Klíčová slova: regroup a flat keyword
// list into topic clusters, each a pillar keyword + supporting keywords —
// ready-made content structure. Generic, so the content-engine module can reuse
// it. Grounded strictly in the supplied keywords; the model invents none.)
// ===========================================================================

/** One supplied keyword fed into clustering — keyword plus optional real metrics
 *  carried over from the keyword-research tool (volume / classified intent). */
export interface KeywordClusterInput {
  /** the keyword phrase (the only required field) */
  keyword: string;
  /** average monthly searches, when known — drives pillar pick + totalVolume */
  volume?: number;
  /** the search intent, when classified (informational | transactional | brand) */
  intent?: string;
}

export interface KeywordClustersRequest {
  /** the keywords to regroup — REAL input set; the model must not invent more */
  keywords: KeywordClusterInput[];
  /** optional overarching topic, to steer the grouping */
  topic?: string;
  /** optional free-text refinement note from a re-run („kratší", „vynech ceny") —
   *  appended to the user prompt only and naturally busts the input-hash cache */
  refine?: string;
}

/** One topic cluster: a single pillar keyword + its supporting keywords, with the
 *  summed monthly volume of every keyword in the cluster. */
export interface KeywordCluster {
  /** short topic name for the cluster */
  topic: string;
  /** the dominant search intent, when the model assigned one */
  intent?: KeywordIntent;
  /** the one pillar keyword (the page to build first) — always from the input */
  pillar: string;
  /** the supporting keywords (the subpages) — all from the input set */
  supporting: string[];
  /** summed monthly searches across pillar + supporting (from supplied volumes) */
  totalVolume?: number;
}

export interface KeywordClustersResult {
  /** the topic clusters, largest (by total volume) first */
  clusters: KeywordCluster[];
}


// ===========================================================================
// Tool 11 — comparison-page outline (Srovnání & SEO: from a chosen high-intent
// comparison query + its intent, generate a publish-ready comparison-page
// scaffold — H1, ordered sections, comparison criteria, verdict and FAQ. NOT a
// generic brief. Scoped to the query + intent (there is no competitor dataset),
// so the model keeps entity names generic / placeholder.)
// ===========================================================================

/** The comparison-query intent, mirrored from lib/seo-compare/sample so the
 *  client+server contract stays free of the sample-data import. */
export type CompareOutlineIntent = "alternative" | "vs" | "pricing" | "review";

/** Czech labels for the intents, surfaced in the prompt and the UI. */
export const COMPARE_INTENT_LABELS: Record<CompareOutlineIntent, string> = {
  alternative: "Alternativa",
  vs: "Srovnání",
  pricing: "Cena",
  review: "Recenze",
};

export interface ComparisonOutlineRequest {
  /** the chosen high-intent comparison query — also the page's primary keyword */
  query: string;
  /** the query's intent, which drives the page framing */
  intent: CompareOutlineIntent;
  /** monthly search volume, when known — surfaced in the prompt for context */
  volume?: number;
  /** the competitor / alternative being compared against — when named, the page
   *  uses it for real instead of a generic placeholder */
  competitor?: string;
  /** the user's own positioning / differentiators — real grounding for "your side"
   *  of the comparison, so the page isn't a blank placeholder skeleton */
  positioning?: string;
  /** optional free-text refinement note from a re-run („kratší", „vynech ceny") —
   *  appended to the user prompt only and naturally busts the input-hash cache */
  refine?: string;
}

/** One section of the comparison page: an H2 heading + the bullet points it covers. */
export interface ComparisonOutlineSection {
  heading: string;
  points: string[];
}

/** A publish-ready comparison-page scaffold (not a generic brief). */
export interface ComparisonOutlineResult {
  /** the page's H1 / display title */
  h1: string;
  /** the ordered sections (heading + points) */
  sections: ComparisonOutlineSection[];
  /** the criteria the solutions are compared against (chips in the UI) */
  comparisonCriteria: string[];
  /** a one-to-two sentence summarising verdict / recommendation */
  verdict: string;
  /** the FAQ (question + answer) for the page */
  faq: { q: string; a: string }[];
}


// ===========================================================================
// Tool 12 — LP variant ideas (LP experimenty: from a topic / keyword context
// generate 2–3 distinct CHALLENGER landing-page variant concepts to test
// against the control. Turns the module's hand-authored variants into
// AI-drafted hypotheses. Scoped to the supplied topic + keywords; the model
// invents no metrics — only concept copy a marketer then ships into a test.)
// ===========================================================================

export interface LpVariantIdeasRequest {
  /** the topic / cluster the landing page targets — the seed for the concepts */
  topic: string;
  /** optional keywords / phrases that further ground the concepts */
  keywords?: string[];
  /** optional label of the control variant the challengers are pitched against */
  controlLabel?: string;
  /** optional short description of the control angle, so challengers differ from it */
  controlDescription?: string;
  /** labels of variant angles already tested that did NOT beat the control — so the
   *  model doesn't re-propose a disproven angle */
  losers?: string[];
  /** the control's conversion rate (0–1) — the bar a challenger must clear */
  controlCvr?: number;
  /** optional free-text refinement note from a re-run („kratší", „vynech ceny") —
   *  appended to the user prompt only and naturally busts the input-hash cache */
  refine?: string;
  /** D4: the project whose lead-quality/CVR data grounds the hypotheses (tenancy-
   *  checked server-side; replaced with the effective keyId for cache tenancy) */
  projectId?: string;
}

/** One AI-drafted challenger concept: a testable angle for a landing-page variant.
 *  All copy only — no traffic / conversion numbers (those come from the real test). */
export interface LpVariantIdea {
  /** short variant label (e.g. „Důraz na šablony“) */
  label: string;
  /** the hypothesis this variant tests (why it might beat the control) */
  hypothesis: string;
  /** a concrete headline draft for the variant */
  headline: string;
  /** the primary call-to-action button copy */
  primaryCTA: string;
  /** one-line rationale tying the concept to the topic / keywords */
  rationale: string;
}

export interface LpVariantIdeasResult {
  /** 2–3 distinct challenger concepts to test against the control */
  variants: LpVariantIdea[];
}


// ===========================================================================
// Tool 13 — lead-source diagnosis (Kvalita leadů: an AI root-cause read of a
// single under-performing / junk lead source. Today „junk" is a single
// hard-coded qualification-rate threshold with no reason; this names WHY the
// source under-performs — spam vs mis-targeting vs pricing/fit — and the one
// concrete action to take. Grounded strictly in the source's real metrics; the
// model invents no figures.)
// ===========================================================================

/** The likely root cause the diagnosis settles on. A constrained set so the UI
 *  can tone / label it consistently; the model's free text lands in summary. */
export const LEAD_SOURCE_CAUSES = ["spam", "mis-targeting", "pricing", "volume", "ok"] as const;
export type LeadSourceCause = (typeof LEAD_SOURCE_CAUSES)[number];

/** Czech labels for the causes — surfaced in the prompt and the UI pill. */
export const LEAD_SOURCE_CAUSE_LABELS: Record<LeadSourceCause, string> = {
  spam: "Spam / nekvalitní leady",
  "mis-targeting": "Špatné cílení (fit)",
  pricing: "Cena / rozpočet",
  volume: "Nízký objem dat",
  ok: "Bez zásadního problému",
};

export const LEAD_SOURCE_CAUSE_LABELS_EN: Record<LeadSourceCause, string> = {
  spam: "Spam / low-quality leads",
  "mis-targeting": "Poor targeting (fit)",
  pricing: "Price / budget",
  volume: "Low data volume",
  ok: "No major issue",
};

export function leadSourceCauseLabel(c: LeadSourceCause, locale: SupportedLocale): string {
  return (locale === "en" ? LEAD_SOURCE_CAUSE_LABELS_EN : LEAD_SOURCE_CAUSE_LABELS)[c];
}

/** The severity the diagnosis assigns — drives the pill tone in the UI. */
export const LEAD_SOURCE_SEVERITIES = ["high", "medium", "low"] as const;
export type LeadSourceSeverity = (typeof LEAD_SOURCE_SEVERITIES)[number];

/** One source's real metrics, flattened to what the diagnosis needs. A
 *  serializable projection of SourceMetrics (lib/lead-quality/compute) so the
 *  client never ships the full source graph to the model. REAL numbers only. */
export interface LeadSourceDiagnosisRequest {
  /** the source label (e.g. „Meta lead formuláře") — also the diagnosis subject */
  source: string;
  /** total leads from the source */
  leads: number;
  /** of those, how many qualified (SQL) */
  qualified: number;
  /** of the qualified, how many closed-won */
  won: number;
  /** qualification rate as a fraction (0–1) = qualified / leads */
  qualRate: number;
  /** win rate as a fraction (0–1) = won / qualified */
  winRate: number;
  /** cost per lead (CZK), when the source has spend */
  cpl?: number;
  /** ad spend (CZK); absent / 0 for unpaid sources */
  spend?: number;
  /** cost per qualified lead (CZK), when the source has spend */
  costPerQualified?: number;
  /** other sources' compact metrics, best-first — lets the diagnosis name a
   *  concrete better source to move budget to instead of a generic "move it" */
  peers?: LeadSourcePeer[];
  /** optional free-text refinement note from a re-run („kratší", „vynech ceny") —
   *  appended to the user prompt only and naturally busts the input-hash cache */
  refine?: string;
}

/** A peer source's compact metrics, for comparison inside the diagnosis (so it can
 *  name a concrete better destination for budget). */
export interface LeadSourcePeer {
  source: string;
  qualRate: number;
  winRate: number;
  /** cost per qualified lead (CZK), when the peer has spend */
  costPerQualified?: number;
}

export interface LeadSourceDiagnosisResult {
  /** one short paragraph reading why the source under-performs */
  summary: string;
  /** the constrained root cause (one of LEAD_SOURCE_CAUSES) */
  likelyCause: LeadSourceCause;
  /** the single most concrete recommended action */
  recommendation: string;
  /** optional severity of the problem */
  severity?: LeadSourceSeverity;
}


// ===========================================================================
// Tool 14 — organic channel research (Kanály: from the project's business
// context — type, brand, offering, localities, competitors, seed keywords —
// produce a RANKED plan of zero-ad-spend visibility channels (directories,
// marketplaces, communities, owned content, PR, partnerships), each with a fit
// score, effort, why it fits THIS business and the concrete first actions.
// Grounded strictly in the supplied context; the model invents no metrics and
// no competitor facts. The OrganicChannel shape is shared with the Kanály module
// so a generated plan can be pinned as the module's source of truth.)
// ===========================================================================

export interface ChannelResearchRequest {
  /** the project type (eshop | app | leadgen | content | local) — steers the channel
   *  mix and the deterministic demo fallback; framed into Czech in the prompt */
  projectType: string;
  /** the brand / business name — grounds the plan in the real business (no invented one) */
  brand: string;
  /** what the business offers (top categories / short offering summary), when known */
  offering?: string;
  /** localities the business serves (local / leadgen) — enables map/directory channels */
  localities?: string[];
  /** named competitors, for gap framing — the model never invents rivals or their numbers */
  competitors?: string[];
  /** seed keywords the audience searches for — grounds content/SEO channels */
  keywords?: string[];
  /** optional free-text refinement note from a re-run („méně kanálů", „víc lokálních") —
   *  appended to the user prompt only and naturally busts the input-hash cache */
  refine?: string;
}

export interface ChannelResearchResult {
  /** one-line strategic read of where the free attention is for this business */
  summary: string;
  /** the ranked organic channels (fit descending), each a ready playbook */
  channels: OrganicChannel[];
}


// ===========================================================================
// Tool 15 — onboarding website scan (Start: from the text of a new user's own
// homepage, extract a structured BUSINESS PROFILE — what they sell, to whom, in
// what voice, plus seed keywords and likely competitors — so one click can seed
// the whole app (competitor set + the profile every grounded module reads) with
// the real business instead of the Mionelo/Dentalis sample. The page text is
// fetched + injected server-side (SSRF-guarded); the model reads ONLY that text
// and must not invent facts the page doesn't support. Competitors are explicitly
// suggestions the user confirms before applying.)
// ===========================================================================

export interface OnboardingScanRequest {
  /** the homepage URL to scan (client-supplied) */
  url: string;
  /** the project type, when known — steers the profile + the demo fallback */
  projectType?: string;
  /** the project / brand name, when known */
  brand?: string;
  /** the extracted homepage text — INJECTED server-side by the route (never trusted
   *  from the client); the prompt is built from it */
  pageText?: string;
  /** the page <title>, injected server-side */
  siteTitle?: string;
  /** the page meta description, injected server-side */
  siteDescription?: string;
  /** optional free-text refinement note from a re-run — appended to the user prompt
   *  only and naturally busts the input-hash cache */
  refine?: string;
}

export interface OnboardingScanResult {
  /** the detected business / brand name */
  businessName: string;
  /** a one-paragraph read of what the business does, from the page */
  summary: string;
  /** what they sell — top categories / offering summary */
  offering: string;
  /** the target audience */
  audience: string;
  /** the brand's tone of voice (a short descriptor) */
  toneOfVoice: string;
  /** seed keywords the audience searches for */
  keywords: string[];
  /** suggested competitors (speculative — the user confirms before applying) */
  competitors: string[];
  /** best-fit project type, when the page makes it clear (eshop|app|leadgen|content|local) */
  suggestedType?: string;
}

