/** Shared contract between the AI route, the Gemini module and the client UI.
 *  Three tools, one envelope. Each tool maps to a Systedo service pillar:
 *    ads      → Výkonnostní reklama
 *    brief    → Tvorba obsahu
 *    analysis → Analýzy a strategie
 */

import type { CampaignPeriod } from "./campaigns/types";

export type AiMode = "ads" | "brief" | "analysis";
export const AI_MODES: AiMode[] = ["ads", "brief", "analysis"];

export interface AiMeta {
  model: string;
  /** true when generated by the deterministic fallback (no provider available:
   *  no Claude CLI in dev / no GEMINI_API_KEY in prod) */
  demo: boolean;
  /** the exact prompt sent to the model — surfaced in the UI for transparency */
  prompt: string;
  tookMs: number;
  /** model tag of the provider that actually served the result */
  provider?: string;
  /** total provider attempts, including retries and any self-repair re-prompt */
  attempts?: number;
  /** true when the environment-preferred provider failed and another provider
   *  (or the deterministic demo) served the result instead */
  fellBack?: boolean;
  /** true when the output was re-prompted once to correct limit violations */
  repaired?: boolean;
  /** limit violations detected in the first model output (before repair/clamp) */
  violations?: string[];
  /** token usage when the provider reports it (Gemini); absent for the Claude
   *  subscription path */
  usage?: { inputTokens: number; outputTokens: number; totalTokens: number };
  /** estimated USD cost of the call; 0 for the dev Claude subscription path */
  estCostUsd?: number;
}

export interface AiResponse<T> {
  result: T;
  meta: AiMeta;
}

// ===========================================================================
// Tool 1 — PPC ads
// ===========================================================================

export const PLATFORMS = ["google", "sklik"] as const;
export const TONES = ["vecny", "pratelsky", "premiovy", "akcni"] as const;

export type Platform = (typeof PLATFORMS)[number];
export type Tone = (typeof TONES)[number];

export const PLATFORM_LABELS: Record<Platform, string> = {
  google: "Google Ads (RSA)",
  sklik: "Sklik (Seznam)",
};

export const TONE_LABELS: Record<Tone, string> = {
  vecny: "Věcný a důvěryhodný",
  pratelsky: "Přátelský a lidský",
  premiovy: "Prémiový a kultivovaný",
  akcni: "Akční a motivující",
};

/** Google Ads character limits — enforced in the prompt and re-checked in the UI. */
export const AD_LIMITS = {
  headline: 30,
  description: 90,
  callout: 25,
  longHeadline: 90,
} as const;

export interface AdRequest {
  product: string;
  benefits: string;
  audience: string;
  platform: Platform;
  tone: Tone;
}

export interface AdResult {
  headlines: string[];
  descriptions: string[];
  callouts: string[];
  keywords: string[];
  longHeadline: string;
  rationale: string;
}

export type AdResponse = AiResponse<AdResult>;

// ===========================================================================
// Tool 2 — SEO content brief
// ===========================================================================

export const CONTENT_TYPES = ["blog", "kategorie", "produkt"] as const;
export type ContentType = (typeof CONTENT_TYPES)[number];

export const CONTENT_TYPE_LABELS: Record<ContentType, string> = {
  blog: "Blogový článek",
  kategorie: "Kategorie e-shopu",
  produkt: "Produktová stránka",
};

/** SEO best-practice limits — checked in the UI like the ad limits. */
export const SEO_LIMITS = {
  titleTag: 60,
  metaDescription: 155,
} as const;

export interface BriefRequest {
  topic: string;
  primaryKeyword: string;
  audience: string;
  contentType: ContentType;
}

export interface BriefResult {
  titleTag: string;
  metaDescription: string;
  h1: string;
  slug: string;
  outline: { heading: string; points: string[] }[];
  faq: { question: string; answer: string }[];
  keywords: string[];
  internalLinks: string[];
  rationale: string;
}

export type BriefResponse = AiResponse<BriefResult>;

// ===========================================================================
// Tool 3 — performance analysis (grounded in the dashboard dataset)
// ===========================================================================

export const ANALYSIS_PERIODS = ["30d", "90d", "12m"] as const;
export type AnalysisPeriod = (typeof ANALYSIS_PERIODS)[number];

export const ANALYSIS_PERIOD_LABELS: Record<AnalysisPeriod, string> = {
  "30d": "30 dní",
  "90d": "90 dní",
  "12m": "12 měsíců",
};

export interface AnalysisRequest {
  period: AnalysisPeriod;
}

export interface AnalysisResult {
  headline: string;
  summary: string;
  wins: string[];
  risks: string[];
  actions: { title: string; detail: string }[];
}

export type AnalysisResponse = AiResponse<AnalysisResult>;

// ===========================================================================
// Tool 4 — campaign / portfolio evaluation (grounded in synced Google Ads data)
// ===========================================================================

export const EVAL_SCOPES = ["campaign", "overall"] as const;
export type EvalScope = (typeof EVAL_SCOPES)[number];

export type EvalPriority = "high" | "medium" | "low";
export const EVAL_PRIORITIES: EvalPriority[] = ["high", "medium", "low"];

export const EVAL_PRIORITY_LABELS: Record<EvalPriority, string> = {
  high: "Vysoká priorita",
  medium: "Střední priorita",
  low: "Nízká priorita",
};

export interface EvalRecommendation {
  title: string;
  detail: string;
  priority: EvalPriority;
}

export interface CampaignReportResult {
  /** one-line verdict */
  verdict: string;
  /** health score 0–100 */
  score: number;
  /** one short paragraph */
  summary: string;
  strengths: string[];
  weaknesses: string[];
  /** prioritised next steps */
  recommendations: EvalRecommendation[];
}

export type CampaignReportResponse = AiResponse<CampaignReportResult>;

/** A stored, persisted evaluation — the shape the API returns and the client
 *  renders. Independent of the SQLite layer so the client never imports server
 *  code. */
export interface CampaignReport {
  scope: EvalScope;
  /** null for the overall / portfolio report */
  campaignId: string | null;
  period: string;
  result: CampaignReportResult;
  meta: AiMeta;
  /** ISO timestamp when the report was generated */
  createdAt: string;
}

/** A lightweight point in a campaign's (or the portfolio's) score history — one
 *  per stored evaluation, ordered oldest → newest. Carries only what the trend
 *  timeline needs so the full report payloads never travel over the wire. */
export interface ReportHistoryPoint {
  /** health score 0–100 at that evaluation */
  score: number;
  /** the one-line verdict, surfaced in the point's tooltip */
  verdict: string;
  /** the data window the evaluation used ("7d" | "30d" | "90d") */
  period: string;
  /** true when produced by the keyless demo fallback */
  demo: boolean;
  /** ISO timestamp when the report was generated */
  createdAt: string;
}

export interface EvaluationRequest {
  scope: EvalScope;
  /** required when scope === "campaign" */
  campaignId?: string;
  period: CampaignPeriod;
}
