/** The per-context routing table, held to the tree.
 *
 *  .github/context-conventions.json says which conventions govern which of the 117
 *  contexts — the join AGENTS.md (repository-wide) and context-map.json
 *  (per-context) never had. It is a ROUTING table, which means its failure mode is
 *  not "wrong", it is "silently no longer pointing at anything": context-map.json is
 *  REGENERATED by the Personas scan, so a rescan that renames a context detaches
 *  every note attached to it, and the file goes on reading exactly as it did.
 *
 *  A routing table that has stopped resolving is worse than none, because a reader
 *  trusts it. So this runs the real resolver — scripts/context-conventions.mjs,
 *  the same code `npm run context:conventions` runs, never a copy — and fails on
 *  anything it cannot resolve.
 *
 *  Rung (docs/adr/0007-gate-rung-discipline.md): BLOCKING. It passes today, so a red
 *  is a regression this change introduced. Inside `npm run test:unit` →
 *  `npm run check:ci` → `.husky/pre-push`.
 *
 *  WHAT IT DELIBERATELY DOES NOT DO: require coverage. Most of the 117 contexts are
 *  governed entirely by the global rules, and a row for each would bury the seven
 *  that say something. Coverage is printed by the command and asserted here only as
 *  a floor, so the table cannot quietly empty out.
 *
 *  Pure — reads files and resolves them. Runs nothing.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { resolveConventions, rowsForPath } from "../scripts/context-conventions.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (rel) => readFileSync(join(ROOT, rel), "utf8");

const REGISTRY_REL = ".github/context-conventions.json";

test("every row resolves — to a context, to a rule, and to a file", () => {
  const { failures } = resolveConventions();
  assert.deepEqual(
    failures,
    [],
    `${failures.length} row(s) in ${REGISTRY_REL} no longer resolve:\n  ${failures.join("\n  ")}\n\n` +
      "context-map.json is regenerated by the Personas scan, so a rescan can rename the context a note is " +
      "attached to without touching the note. Re-point the row at where the code went."
  );
});

test("the table still routes the contexts it was written for", () => {
  const { rows, totalContexts } = resolveConventions();
  assert.ok(totalContexts > 50, `context-map.json declares ${totalContexts} contexts — the map itself looks wrong.`);
  assert.ok(
    rows.length >= 5,
    `${REGISTRY_REL} carries ${rows.length} row(s). Below a handful this stops being a routing table and becomes ` +
      "a file somebody forgot to delete."
  );
  // The seams where a global document is demonstrably not enough: the LLM
  // chokepoint (the demo fallback is a product property), the dual store (a
  // Firestore-only method is invisible offline), and the ad-write rails (RED under
  // AGENTS.md § What you may do unattended). Dropping one is an argument to make,
  // not a cleanup.
  const named = new Set(rows.map((r) => r.name));
  for (const id of ["llm-core-providers", "campaigns-store-backend", "campaigns-sklik-sync"]) {
    assert.ok(
      named.has(id),
      `${REGISTRY_REL} no longer routes \`${id}\`. That is one of the contexts whose local conventions cost the ` +
        "most to rediscover — say why it no longer needs a row."
    );
  }
});

test("the unfenced notes are marked, because those are the ones worth reading", () => {
  // A note about a rule a gate already blocks is a convenience. A note about a rule
  // where NOTHING would tell you that you got it wrong is the only reason this file
  // beats reading AGENTS.md again, and the reader prints it differently.
  const { rows } = resolveConventions();
  const unfenced = rows.flatMap((r) => (r.entry.local ?? []).filter((n) => n.unfenced === true));
  assert.ok(
    unfenced.length >= 5,
    `${REGISTRY_REL} marks ${unfenced.length} note(s) \`unfenced\`. Those are the traps where a red build will ` +
      "never arrive — if they have all gained fences, say so in the row rather than dropping the flag."
  );
  for (const r of rows) {
    for (const note of r.entry.local ?? []) {
      assert.ok(
        typeof note.unfenced === "boolean",
        `${r.name}: a local note does not say whether it is fenced. "Will anything notice if I get this wrong?" ` +
          "is the whole question a reader brings to this file."
      );
    }
  }
});

test("a path resolves to the conventions that govern it — the question an agent actually asks", () => {
  // The reason this is a machine-readable file and not seven more paragraphs in
  // AGENTS.md: an agent has a file open, not a context name.
  const { rows } = resolveConventions();
  const llm = rowsForPath(rows, "src/lib/llm/index.ts");
  assert.ok(
    llm.some((r) => r.name === "llm-core-providers"),
    "src/lib/llm/index.ts no longer resolves to llm-core-providers, so `npm run context:conventions -- --path` " +
      "answers nothing for the one seam every AI feature passes through."
  );
  // A file no row claims must answer cleanly rather than by guessing at a neighbour.
  assert.deepEqual(
    rowsForPath(rows, "README.md"),
    [],
    "a path no context claims resolved to a row anyway — a routing table that guesses is one that misleads."
  );
});

test("the reader exists, is wired, and is named where an agent will meet it", () => {
  const pkg = JSON.parse(read("package.json"));
  assert.ok(
    pkg.scripts["context:conventions"],
    "package.json defines no `context:conventions`, so the table has no reader and stops being consulted."
  );
  assert.ok(
    pkg.scripts["context:conventions:check"],
    "package.json defines no `context:conventions:check` — the routing has no way to be verified on demand."
  );
  assert.match(
    read("AGENTS.md"),
    /context-conventions\.json/,
    "AGENTS.md no longer names .github/context-conventions.json. A routing table nothing routes TO is one nobody " +
      "opens, and the canonical document is where a run looks first."
  );
});
