/** The per-context test census, held to the tree.
 *
 *  The suite's strength is measured for the REPOSITORY — 515 files, a healthy ratio,
 *  a mutation drill on six seams. The unit an agent works in is the CONTEXT, and a
 *  whole context with no test pointing at it does not move a repository-wide number
 *  enough to notice. scripts/context-coverage.mjs measures it per context;
 *  .github/context-test-floors.json is the half that blocks.
 *
 *  Rung (docs/adr/0007-gate-rung-discipline.md): BLOCKING, and only for the floors.
 *  Five contexts — the LLM chokepoint, the metering, the campaign store backend, the
 *  Sklik write path and the cron spine — may not fall to zero claimed files. Every
 *  one of them passes today, so a red here is a regression this change introduced.
 *  The TOTAL is reporting: it carries no accepted ceiling until somebody has run the
 *  census, because a baseline invented without measuring is what tsconfig.strict.json
 *  names as the thing that must not happen.
 *
 *  The floors' other failure mode is the quiet one and it is asserted separately: a
 *  floor naming a context the Personas scan has renamed guards nothing while
 *  continuing to read as a guard.
 *
 *  Pure — reads files and runs nothing.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  FLOORS_REL,
  census,
  checkFloors,
  claimTokens,
  readTestSources,
  reasonProblem,
  uncoveredRows,
} from "../scripts/context-coverage.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (rel) => readFileSync(join(ROOT, rel), "utf8");

// Measured once: reading ~530 test sources and 117 contexts is the expensive half,
// and every assertion below asks a question of the same census.
const sources = readTestSources();
const { rows, totalContexts, tests } = census({ sources });
const floors = JSON.parse(read(FLOORS_REL));

test("the census can see the map and the suite at all", () => {
  assert.ok(
    totalContexts > 50,
    `context-map.json declares ${totalContexts} contexts — the map itself, or the way this reads it, looks wrong.`
  );
  assert.ok(
    tests > 100,
    `only ${tests} test source(s) were found. A census that cannot see the suite reports every context as ` +
      "uncovered, which is a finding about this file rather than about the tree."
  );
  const withSource = rows.filter((r) => !r.sourceless);
  assert.ok(
    withSource.length > 50,
    `only ${withSource.length} context(s) map any file under src/. The map's file_paths are what this measures.`
  );
});

test("every floor still resolves to a context the map has", () => {
  const { routing } = checkFloors({ rows, floors });
  assert.deepEqual(
    routing,
    [],
    `${routing.length} floor(s) in ${FLOORS_REL} no longer resolve:\n  ${routing.join("\n  ")}\n\n` +
      "context-map.json is regenerated by the Personas scan, so a rescan can rename the context a floor guards " +
      "without touching the floor — after which it reads as a guard and guards nothing."
  );
});

test("every floor is met — the contexts where zero tests is a bill, a breach or a credential", () => {
  const { breaches } = checkFloors({ rows, floors });
  assert.deepEqual(
    breaches.map((b) => `${b.name}: ${b.claimed} of ${b.files} claimed, floor ${b.min}`),
    [],
    "a context with a floor has nothing pointing at it. Write the test; lowering the floor is rubric B3, and " +
      "these are the contexts AGENTS.md § Red is about.\n" +
      "  npm run context:coverage -- --context <name>"
  );
});

test("the floors still cover the seams they were written for", () => {
  const named = new Set((floors.floors ?? []).map((f) => f.context));
  for (const id of [
    "llm-core-providers",
    "ai-pipeline-limits",
    "campaigns-store-backend",
    "campaigns-sklik-sync",
    "cron-jobs",
  ]) {
    assert.ok(
      named.has(id),
      `${FLOORS_REL} no longer floors \`${id}\`. Dropping a floor is an argument to make in the diff — say what ` +
        "now stops that context from losing its last test."
    );
  }
  for (const floor of floors.floors ?? []) {
    assert.ok(
      Number.isInteger(floor.minClaimedFiles) && floor.minClaimedFiles >= 1,
      `${FLOORS_REL}: \`${floor.context}\` declares minClaimedFiles ${floor.minClaimedFiles}, which cannot fail.`
    );
  }
});

test("the checker still BITES — an unmet floor is caught, not reported as met", () => {
  // The property that stops this rotting into a green nobody has seen fail. A census
  // that silently claims everything reads exactly like a tree with nothing wrong.
  const fixtureRows = [
    { name: "empty-context", group: "g", category: "lib", files: 4, claimed: 0, unclaimed: ["src/a.ts"], sourceless: false },
  ];
  const { breaches } = checkFloors({
    rows: fixtureRows,
    floors: { floors: [{ context: "empty-context", minClaimedFiles: 1, why: "a fixture whose only job is to be below its floor, so the checker is seen to fail" }] },
  });
  assert.equal(breaches.length, 1, "a context with zero claimed files passed a floor of 1 — the checker is not checking.");

  const gone = checkFloors({
    rows: fixtureRows,
    floors: { floors: [{ context: "renamed-away", minClaimedFiles: 1, why: "a fixture naming a context the map does not have, so the routing failure is seen" }] },
  });
  assert.equal(gone.routing.length, 1, "a floor naming a context that does not exist resolved anyway.");
});

test("a claim is a NAMED path, not a filename that half the tree shares", () => {
  const tokens = claimTokens('import { x } from "@/lib/cron/fan-out";\n// see src/lib/db.ts.\nconst r = "route";');
  assert.ok(tokens.has("src/lib/cron/fan-out"), "an `@/` specifier did not resolve to the src/ path it names.");
  assert.ok(tokens.has("src/lib/db"), "a repo path in prose was not recognised, so doc comments claim nothing.");
  assert.ok(!tokens.has("route"), "a bare filename became a claim — that would report the whole App Router as covered.");
});

test("the total is reporting until somebody measures it, and the floors decide meanwhile", () => {
  // ADR-0007 in the one place it is easiest to get wrong: this file could invent a
  // ceiling that has never been run, and it would look identical to a measured one.
  const uncovered = uncoveredRows(rows);
  assert.ok(Array.isArray(uncovered), "the uncovered census did not produce a list.");
  if (floors.accepted == null) {
    assert.deepEqual(floors.history ?? [], [], `${FLOORS_REL} has history but no accepted count — one of them is wrong.`);
  } else {
    assert.ok(
      typeof floors.accepted.uncovered === "number" && typeof floors.accepted.reason === "string",
      `${FLOORS_REL}: an accepted ceiling with no count or no reason is a number nobody can argue with.`
    );
    assert.ok(
      uncovered.length <= floors.accepted.uncovered,
      `${uncovered.length} context(s) have no test pointing at them, above the accepted ${floors.accepted.uncovered}.`
    );
  }
  assert.equal(reasonProblem("wip"), 'the reason "wip" is too short to tell a future reader what was measured and why.');
});

test("the reader exists, is wired, and is named where an agent will meet it", () => {
  const pkg = JSON.parse(read("package.json"));
  assert.ok(pkg.scripts["context:coverage"], "package.json defines no `context:coverage`, so the census has no reader.");
  assert.ok(
    pkg.scripts["context:coverage:check"],
    "package.json defines no `context:coverage:check` — the floors have no way to be run on demand."
  );
  assert.match(
    read("AGENTS.md"),
    /context-test-floors\.json/,
    "AGENTS.md no longer names .github/context-test-floors.json. A census nothing routes to is one nobody opens."
  );
});
