"use client";

import { useState } from "react";
import { Button } from "@/components/ui";
import { useT } from "@/lib/i18n/client";
import { PrototypeChrome, PrototypeFooter } from "./PrototypeChrome";

const T = {
  cs: { eyebrow: "MARKETING S JASNÝM SMĚREM", title: "Méně šumu.\nVíce směru.", sub: "Jeden web. Jasný plán. Od první příležitosti zdarma až po kampaně, které máte pod kontrolou.", cta: "Najít svůj další krok", demo: "Prozkoumat ukázku", console: "PŘEHLED PŘÍLEŽITOSTÍ", sample: "UKÁZKOVÁ DATA", project: "Pražírna / Praha", live: "Ukázkový projekt", free: "Objevit", create: "Připravit", measure: "Vyhodnotit", freeTitle: "Začněte tam, kde vás hledají.", createTitle: "Z příležitosti vznikne obsah.", measureTitle: "Z dat vznikne další krok.", channel: "KANÁL", next: "DALŠÍ KROK", fit: "SHODA", item1: "Google Business Profile", item2: "Firmy.cz", item3: "Lokální komunity", action1: "Doplnit firemní profil", action2: "Připravit zápis", action3: "Vybrat vhodnou komunitu", high: "Vysoká", medium: "Střední", source: "VAŠE ZNAČKA", opportunities: "PŘÍLEŽITOSTI", result: "PRVNÍ KROK", selected: "VYBRANÁ PŘÍLEŽITOST", detail1: "Přidejte otevírací dobu, fotografie a odkaz na svůj web.", detail2: "Připravte popis pražírny a vyberte odpovídající kategorii.", detail3: "Najděte relevantní skupinu a nejprve poznejte její pravidla.", why: "Smysl v každém kroku.", how1: "Objevte", how2: "Připravte", how3: "Vyhodnoťte", desc1: "Kde vás mohou najít bez placené reklamy.", desc2: "Obsah, který vychází z vaší značky.", desc3: "Placené kanály v souvislostech.", article: "Článek", post: "Příspěvek", draft: "Návrh ke kontrole", headline: "Jak vybrat kávu na doma", impressions: "Zobrazení", clicks: "Kliknutí", conversions: "Konverze", end: "Váš další krok\nuž nemusí být odhad.", noaccount: "Bez reklamního účtu. Zdarma během ověřování produktu." },
  en: { eyebrow: "MARKETING WITH A SENSE OF DIRECTION", title: "Less noise.\nMore signal.", sub: "One website. A clear plan. From your first free opportunity to campaigns you can actually steer.", cta: "Find my next move", demo: "Explore the demo", console: "OPPORTUNITY OVERVIEW", sample: "SAMPLE DATA", project: "Coffee roaster / Prague", live: "Sample project", free: "Discover", create: "Create", measure: "Measure", freeTitle: "Start where they’re looking.", createTitle: "Turn an opportunity into content.", measureTitle: "Turn your data into a next move.", channel: "CHANNEL", next: "NEXT MOVE", fit: "FIT", item1: "Google Business Profile", item2: "Firmy.cz", item3: "Local communities", action1: "Complete business profile", action2: "Prepare a listing", action3: "Choose a relevant community", high: "High", medium: "Medium", source: "YOUR BRAND", opportunities: "OPPORTUNITIES", result: "FIRST MOVE", selected: "SELECTED OPPORTUNITY", detail1: "Add opening hours, photos and a link to your website.", detail2: "Prepare a roaster description and choose a relevant category.", detail3: "Find a relevant group and get to know its rules first.", why: "Every move has a reason.", how1: "Discover", how2: "Create", how3: "Measure", desc1: "Places to be found without buying ads.", desc2: "Content that starts with your brand.", desc3: "Paid channels, seen in context.", article: "Article", post: "Social post", draft: "Draft for review", headline: "How to choose coffee for home", impressions: "Impressions", clicks: "Clicks", conversions: "Conversions", end: "Your next move.\nMinus the guesswork.", noaccount: "No ad account needed. Free during product validation." },
} as const;

export default function Signal() {
  const t = useT(T);
  const [mode, setMode] = useState<"free" | "create" | "measure">("free");
  const [selected, setSelected] = useState(0);
  return <div className="proto signal"><PrototypeChrome active="signal" />
    <section className="signal-hero"><div><p className="proto-eyebrow"><i className="status-dot" />{t("eyebrow")}</p><h1>{t("title")}</h1></div><div className="signal-intro"><p>{t("sub")}</p><Button href="/kanaly-zdarma" className="proto-cta">{t("cta")} ↗</Button><a href="#console">{t("demo")} ↓</a></div></section>
    <section className="signal-console" id="console"><header><span><i className="status-dot" /> ADAMANT / {t("console")}</span><span className="sample-label">{t("sample")}</span></header><div className="console-body"><aside><span className="console-project">◈</span><b>{t("project")}</b><small>{t("live")}</small><div className="console-tabs" role="group" aria-label={t("console")}>{(["free", "create", "measure"] as const).map((key, i) => <Button variant="ghost" key={key} onClick={() => setMode(key)} aria-pressed={mode === key}><span>0{i + 1}</span>{t(key)}<span>↗</span></Button>)}</div><div className="console-mini-map" aria-hidden="true"><i /><i /><i /><b>◈</b></div></aside>
      <div className="console-main" aria-live="polite"><h2>{t(`${mode}Title`)}</h2>{mode === "free" ? <><div className="signal-flow" aria-hidden="true"><div><span>◈</span><small>{t("source")}</small></div><i /><div><span>◎</span><small>{t("opportunities")}</small></div><i /><div><span>↗</span><small>{t("result")}</small></div></div><div className="opportunity-head"><span>{t("channel")}</span><span>{t("next")}</span><span>{t("fit")}</span></div>{[0, 1, 2].map(i => <Button variant="ghost" className="opportunity-row" key={i} onClick={() => setSelected(i)} aria-pressed={selected === i}><span><i>{["G", "F", "◎"][i]}</i>{t(`item${i + 1}` as "item1")}</span><span>{t(`action${i + 1}` as "action1")}</span><span className="fit-badge">{t(i === 2 ? "medium" : "high")} ↗</span></Button>)}<div className="signal-selected"><span>↳ {t("selected")}</span><p>{t(`detail${selected + 1}` as "detail1")}</p></div></> : mode === "create" ? <div className="signal-drafts">{["article", "post"].map((key, i) => <article key={key}><small>{t(key as "article")} / 0{i + 1}</small><div className="draft-art" aria-hidden="true">{i ? "✳" : "◒"}</div><h3>{t("headline")}</h3><p>◌ {t("draft")}</p></article>)}</div> : <div className="signal-metrics"><div>{["impressions", "clicks", "conversions"].map((key, i) => <article key={key}><small>{t(key as "clicks")}</small><b>{["12 480", "624", "31"][i]}</b></article>)}</div><svg viewBox="0 0 640 210" role="img" aria-label={`${t("sample")} — ${t("clicks")}`}><path className="chart-grid" d="M0 40H640M0 90H640M0 140H640M0 190H640"/><path className="chart-area" d="M0 180L55 163L100 170L150 125L200 140L260 90L310 110L365 66L420 82L475 40L530 55L585 20L640 10V210H0Z"/><path className="chart-line" d="M0 180L55 163L100 170L150 125L200 140L260 90L310 110L365 66L420 82L475 40L530 55L585 20L640 10"/></svg><small>Google Ads + Sklik / {t("sample")}</small></div>}</div></div>
    </section><section className="signal-how" id="how"><p className="proto-eyebrow">01 / 02 / 03</p><h2>{t("why")}</h2><div>{[1, 2, 3].map(i => <article key={i}><span className="signal-step-art" aria-hidden="true">{["◎", "✳", "↗"][i - 1]}</span><small>0{i}</small><h3>{t(`how${i}` as "how1")}</h3><p>{t(`desc${i}` as "desc1")}</p></article>)}</div></section><section className="proto-closing"><h2>{t("end")}</h2><p>{t("noaccount")}</p><Button href="/kanaly-zdarma" className="proto-cta">{t("cta")} ↗</Button></section><PrototypeFooter />
  </div>;
}
