/** The actual output, not a picture of it — the seeded channel plan the public
 *  demo renders, straight out of `channelPlanForProject` (see ./facts).
 *
 *  Why real seeds and not a mock table: the channel names, fit scores, effort
 *  levels and first actions on this page ARE the product's data. Nothing is typed
 *  twice, so a curated channel that changes in `sample.ts` changes here, and a
 *  claim on this page can never outlive the code behind it.
 *
 *  Honesty: the plan is a SEEDED sample for a fictional demo e-shop, labelled as
 *  such — the same framing the homepage proof band uses. A real tenant's plan is
 *  personalized to their own scan and can be regenerated by the model. */
import Link from "next/link";
import { Container, Eyebrow, Pill } from "@/components/ui";
import { ArrowRight } from "@/components/icons";
import { CATEGORY_LABELS, EFFORT_LABELS } from "@/components/app/channels/labels";
import { getT } from "@/lib/i18n/server";
import { getServerLocale } from "@/lib/i18n/locale";
import type { FreeChannelFacts } from "./facts";

/** How many rows the page shows. The rest stay in the module — the point is to
 *  show the shape of the answer, not to reprint the whole plan. */
const SHOWN = 6;

const T = {
  cs: {
    eyebrow: "Výstup",
    heading: "Takhle plán vypadá.",
    note: "Seřazeno podle toho, jak kanál sedí konkrétní firmě. Prvních {shown} z {total} kanálů, které modul pro tento projekt sestaví.",
    demoBadge: "Ukázková data: fiktivní klient",
    provenance:
      "Plán je pro {brand} ({domain}), fiktivního ukázkového e-shopu. Kanály, hodnocení i první kroky jsou kurátorované osivo modulu — reálný projekt dostane plán opřený o sken vlastního webu a může si ho nechat přegenerovat modelem.",
    colChannel: "Kanál",
    colFamily: "Rodina",
    colFit: "Sedne",
    colEffort: "Náročnost",
    colFirst: "První krok",
    cta: "Projít celý plán v ukázce",
  },
  en: {
    eyebrow: "The output",
    heading: "This is what the plan looks like.",
    note: "Ranked by how well each channel fits this specific business. The first {shown} of {total} channels the module builds for this project.",
    demoBadge: "Demo data: fictional client",
    provenance:
      "The plan is for {brand} ({domain}), a fictional demo e-shop. The channels, scores and first steps are the module's curated seed — a real project gets a plan grounded in a scan of its own site, and can have the model rebuild it.",
    colChannel: "Channel",
    colFamily: "Family",
    colFit: "Fit",
    colEffort: "Effort",
    colFirst: "First step",
    cta: "Walk the whole plan in the demo",
  },
} as const;

export default async function SeededPlanTable({ facts }: { facts: FreeChannelFacts }) {
  const t = await getT(T);
  const locale = await getServerLocale();
  const { project, plan } = facts.demo;
  const rows = plan.slice(0, SHOWN);

  return (
    <section className="border-b border-line">
      <Container className="py-14 lg:py-20">
        <div className="flex flex-wrap items-end justify-between gap-4">
          <div className="max-w-xl">
            <Eyebrow>{t("eyebrow")}</Eyebrow>
            <h2 className="mt-3 text-2xl font-semibold tracking-tight text-navy-800 sm:text-3xl">
              {t("heading")}
            </h2>
            <p className="mt-3 text-sm text-muted">
              {t("note", { shown: String(rows.length), total: String(plan.length) })}
            </p>
          </div>
          <Pill tone="navy">{t("demoBadge")}</Pill>
        </div>

        <div className="mt-8 overflow-x-auto rounded-2xl border border-line bg-surface shadow-card">
          <table className="w-full min-w-[46rem] border-collapse text-left text-sm">
            <thead>
              <tr className="border-b border-line text-[11px] font-semibold uppercase tracking-[0.12em] text-muted">
                <th scope="col" className="px-4 py-3">{t("colChannel")}</th>
                <th scope="col" className="px-4 py-3">{t("colFamily")}</th>
                <th scope="col" className="px-4 py-3 text-right">{t("colFit")}</th>
                <th scope="col" className="px-4 py-3">{t("colEffort")}</th>
                <th scope="col" className="px-4 py-3">{t("colFirst")}</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((c) => {
                const effort = EFFORT_LABELS[c.effort];
                return (
                  <tr key={c.id} className="border-b border-line last:border-b-0 align-top">
                    <td className="px-4 py-3.5">
                      <span className="block font-semibold text-navy-800">{c.name}</span>
                      <span className="mt-0.5 block max-w-md text-[13px] leading-relaxed text-muted">
                        {c.payoff}
                      </span>
                    </td>
                    <td className="px-4 py-3.5 text-muted">
                      {CATEGORY_LABELS[c.category][locale] ?? CATEGORY_LABELS[c.category].en}
                    </td>
                    <td className="tnum px-4 py-3.5 text-right font-semibold text-brand-accent">
                      {c.fit}
                    </td>
                    <td className="px-4 py-3.5">
                      <span className={`pill ${effort.tone}`}>{effort[locale] ?? effort.en}</span>
                    </td>
                    <td className="px-4 py-3.5 max-w-sm text-[13px] leading-relaxed text-navy-700">
                      {c.firstActions[0]}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>

        <div className="mt-5 flex flex-wrap items-center justify-between gap-4">
          <p className="max-w-2xl text-xs leading-relaxed text-muted">
            {t("provenance", { brand: project.name, domain: project.domain ?? "" })}
          </p>
          <Link
            href="/dashboard?m=kanaly"
            className="inline-flex shrink-0 items-center gap-2 text-sm font-semibold text-brand-accent transition-colors hover:text-brand-800"
          >
            {t("cta")}
            <ArrowRight width={16} height={16} />
          </Link>
        </div>
      </Container>
    </section>
  );
}
