#!/usr/bin/env node
/** Which decision governs THIS file? — the reverse of docs/task-index.md.
 *
 *  WHAT WAS MISSING. `docs/task-index.md` routes from a task to the record that
 *  decides it, and its last table lists every ADR by the seam it governs. Both are
 *  written for a reader who has already framed the work: "I am about to change the
 *  store seam" finds ADR-0001 in one line. The lookup that had no answer is the one
 *  that actually happens — an agent is three files into a change, has never framed
 *  it as a seam at all, and nothing in the tree tells it that `src/lib/db.ts` is
 *  governed by a decision somebody argued and wrote down. A record found only by
 *  whoever thought to look for one is prose with a number on it.
 *
 *  So the mapping is declared in `.github/adr-ownership.json` and read from the
 *  direction a reader has: a path in, the records that govern it out.
 *
 *      npm run adr:owner -- src/lib/campaigns/store.ts
 *      npm run adr:owner -- --unmapped        # subtrees no record claims
 *      npm run adr:owner -- --check           # the audit the unit suite runs
 *
 *  WHY A DECLARATION AND NOT A DERIVATION. Whether a module is "under" a decision is
 *  a judgment — an import graph cannot tell a store module that inherits ADR-0001
 *  from a helper that merely calls one. So it is written, and the two ways a written
 *  mapping rots are fenced instead: a record with no row cannot land (every file in
 *  `docs/adr/` must appear), and a row naming a path that has moved goes red. That
 *  is the same property `npm run adr:check` gives to the paths an ADR cites in its
 *  prose; this extends it to the ones it governs.
 *
 *  WHY NOT context-map.json, which was the obvious home. That file is REGENERATED by
 *  the Personas context scan, so a hand-added `adrs:` key on a context is a key the
 *  next scan drops — silently, and in a file nobody diffs closely because most of it
 *  is machine-written. A declaration that a generator owns is the wrong place for a
 *  fact a human decides.
 *
 *  RUNG (docs/adr/0007-gate-rung-discipline.md). The audit is BLOCKING and green on
 *  arrival — it runs inside `npm run test:unit` via
 *  test-unit/adr-ownership.test.mjs. `--unmapped` is REPORTING and always will be:
 *  the question it asks ("has a record come to govern code nobody mapped?") has no
 *  derivable answer, so it prints a list to read rather than a count to satisfy.
 */
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OWNERSHIP_REL = ".github/adr-ownership.json";
const ADR_DIR_REL = "docs/adr";

/** Repo-relative, forward slashes, no leading `./` — the form every entry in the
 *  declaration is written in, so a Windows path and a pasted URL fragment compare
 *  the same way. */
export function normalise(path) {
  const raw = String(path ?? "").trim().replace(/\\/g, "/").replace(/^\.\//, "");
  if (!raw) return "";
  if (/^[A-Za-z]:\//.test(raw) || raw.startsWith("/")) {
    return relative(ROOT, resolve(raw)).split(sep).join("/");
  }
  return raw.replace(/\/+$/, "");
}

/** Prefix matching on whole path SEGMENTS: `src/lib/projects` governs
 *  `src/lib/projects/store.ts` and never `src/lib/projects-legacy.ts`. */
export const governs = (entry, path) => path === entry || path.startsWith(`${entry}/`);

export function loadOwnership(root = ROOT) {
  const abs = join(root, OWNERSHIP_REL);
  if (!existsSync(abs)) {
    throw new Error(`${OWNERSHIP_REL} is missing — it is the declaration this lookup reads.`);
  }
  return JSON.parse(readFileSync(abs, "utf8"));
}

/** Every record that governs `path`, most specific entry first. */
export function recordsFor(path, ownership) {
  const target = normalise(path);
  const hits = [];
  for (const record of ownership.records ?? []) {
    const matched = (record.governs ?? []).filter((entry) => governs(entry, target));
    if (matched.length) hits.push({ record, matched });
  }
  return hits.sort(
    (a, b) => Math.max(...b.matched.map((m) => m.length)) - Math.max(...a.matched.map((m) => m.length))
  );
}

/** The audit, as data, so the unit suite and the CLI cannot hold two opinions. */
export function auditOwnership(root = ROOT) {
  const problems = [];
  let ownership;
  try {
    ownership = loadOwnership(root);
  } catch (err) {
    return { problems: [err.message], ownership: null };
  }

  const rows = ownership.records ?? [];
  if (!rows.length) problems.push(`${OWNERSHIP_REL} declares no records — an empty reverse index routes nothing.`);

  const adrDir = join(root, ADR_DIR_REL);
  const onDisk = existsSync(adrDir)
    ? readdirSync(adrDir)
        .filter((f) => /^\d{4}-[a-z0-9-]+\.md$/.test(f))
        .map((f) => `${ADR_DIR_REL}/${f}`)
    : [];

  const claimed = new Set();
  for (const row of rows) {
    const adr = normalise(row.adr);
    if (!adr) {
      problems.push(`${OWNERSHIP_REL}: a row has no \`adr\`, so nothing can be looked up through it.`);
      continue;
    }
    if (claimed.has(adr)) problems.push(`${OWNERSHIP_REL}: ${adr} has more than one row.`);
    claimed.add(adr);
    if (!existsSync(join(root, adr))) {
      problems.push(`${OWNERSHIP_REL}: ${adr} does not exist. A reverse index pointing at a record that has moved sends a reader nowhere.`);
    }
    if (!String(row.seam ?? "").trim()) {
      problems.push(`${adr}: no \`seam\`. The row's whole job is to say, in one line, what a reader is about to change.`);
    }

    const entries = row.governs ?? [];
    if (!entries.length) {
      if (!String(row.whyNothing ?? "").trim()) {
        problems.push(
          `${adr}: governs no path and gives no \`whyNothing\`. A record that governs nothing is a fine thing to ` +
            "be — a decision about process rather than about code — but it has to SAY so, or it reads as a row " +
            "somebody forgot to fill in, and the next reader cannot tell those apart."
        );
      }
      continue;
    }
    if (!String(row.why ?? "").trim()) {
      problems.push(`${adr}: no \`why\`. Which files a decision governs is the claim; why they are the ones is the part that can be checked by a reader.`);
    }
    for (const entry of entries) {
      if (entry !== normalise(entry)) {
        problems.push(`${adr}: \`${entry}\` is not a repo-relative path with forward slashes.`);
        continue;
      }
      if (!existsSync(join(root, entry))) {
        problems.push(
          `${adr}: governs \`${entry}\`, which does not exist in the tree. A rename is exactly when nobody ` +
            "thinks to look at a decision record — update the row, or move the record's Status if the seam is gone."
        );
      }
    }
  }

  for (const adr of onDisk) {
    if (!claimed.has(adr)) {
      problems.push(
        `${adr}: no row in ${OWNERSHIP_REL}. A record nobody can reach from the file it governs is found only by ` +
          "whoever already knew it existed — write the row, or state `governs: []` with a `whyNothing`."
      );
    }
  }

  return { problems, ownership };
}

/** Reporting only. The subtrees under the roots below that no record claims — the
 *  half of this question that cannot be derived, printed rather than counted. */
export function unmappedSubtrees(ownership, root = ROOT, roots = ["src/lib", "src/app", "scripts", ".github"]) {
  const entries = (ownership.records ?? []).flatMap((r) => r.governs ?? []);
  const out = [];
  for (const base of roots) {
    const abs = join(root, base);
    if (!existsSync(abs)) continue;
    for (const name of readdirSync(abs)) {
      const rel = `${base}/${name}`;
      if (name.startsWith(".")) continue;
      let isDir = false;
      try {
        isDir = statSync(join(root, rel)).isDirectory();
      } catch {
        continue;
      }
      if (!isDir) continue;
      const covered = entries.some((entry) => governs(entry, rel) || governs(rel, entry));
      if (!covered) out.push(rel);
    }
  }
  return out;
}

// --- CLI ----------------------------------------------------------------------

const invokedDirectly = process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));

if (invokedDirectly) {
  const argv = process.argv.slice(2);
  const CHECK = argv.includes("--check");
  const UNMAPPED = argv.includes("--unmapped");
  const targets = argv.filter((a) => !a.startsWith("--"));

  const { problems, ownership } = auditOwnership();

  if (CHECK) {
    if (problems.length) {
      console.error(`✗ adr:owner: ${problems.length} problem(s) in the reverse index\n`);
      for (const p of problems) console.error(`  • ${p}`);
      console.error(
        `\n  → what to do next:\n` +
          `      npm run adr:owner -- <path>        # what the index answers today\n` +
          `      Edit ${OWNERSHIP_REL}: a record needs a row, and a row's paths have to exist.\n` +
          "      A record whose seam is gone is superseded by a new ADR — not deleted from this file.\n"
      );
      process.exit(1);
    }
    console.log(
      `✓ adr:owner: ${ownership.records.length} record(s), each reachable from the paths it governs, and every ` +
        "governed path still in the tree."
    );
    process.exit(0);
  }

  if (UNMAPPED) {
    const unmapped = unmappedSubtrees(ownership);
    console.log("Subtrees no decision record claims (REPORTING — nothing goes red for this):\n");
    if (!unmapped.length) console.log("  (none)");
    for (const rel of unmapped) console.log(`  ${rel}`);
    console.log(
      "\nMost of these are correct: most code is not governed by a decision. Read it as the question it is —\n" +
        "has one of these grown into a seam a record already decides, without anybody mapping it? If so, add\n" +
        `the path to the record's row in ${OWNERSHIP_REL}.`
    );
    process.exit(0);
  }

  if (!targets.length) {
    console.log("Which decision governs a file?\n");
    console.log("  npm run adr:owner -- <path>        e.g. src/lib/db.ts");
    console.log("  npm run adr:owner -- --unmapped    subtrees no record claims (reporting)");
    console.log("  npm run adr:owner -- --check       the audit the unit suite runs\n");
    console.log(`The declaration is ${OWNERSHIP_REL}; the forward index is ${ownership?.index ?? "docs/task-index.md"}.\n`);
    for (const row of ownership?.records ?? []) {
      console.log(`  ${row.adr}`);
      console.log(`    ${row.seam}`);
      console.log(`    governs: ${(row.governs ?? []).join(", ") || "(nothing — " + (row.whyNothing ?? "") + ")"}`);
    }
    process.exit(0);
  }

  let missed = 0;
  for (const target of targets) {
    const hits = recordsFor(target, ownership);
    console.log(`\n${normalise(target)}`);
    if (!hits.length) {
      missed += 1;
      console.log("  no decision record claims this path.");
      console.log("  That is the usual answer and not a warning — most code here is not governed by an ADR.");
      console.log(`  If you believe one does, the row to extend is in ${OWNERSHIP_REL}.`);
      continue;
    }
    for (const { record, matched } of hits) {
      console.log(`  ${record.adr}`);
      console.log(`    ${record.seam}`);
      console.log(`    matched: ${matched.join(", ")}`);
      if (record.why) console.log(`    why: ${record.why}`);
    }
  }
  console.log("");
  if (missed && problems.length) {
    console.error("(the reverse index itself has problems — run `npm run adr:owner -- --check`)");
  }
}
