#!/usr/bin/env node
/** Agent instruction-surface gate (zero-dependency).
 *
 *  Part of the instruction surface agents read is not written by this team:
 *
 *    • AGENTS.md opens with a block that `next dev` writes and RE-ADDS. Delete it
 *      and the next dev server puts it back, so it lands in whatever diff happens
 *      to be open at the time.
 *    • CLAUDE.md's "Project Context Map" section is regenerated by the Personas
 *      context scan and states, as fact, how many contexts exist.
 *
 *  Both are guarded by CODEOWNERS, which is the right instinct and not enough: a
 *  file that regenerates itself is only reviewed if somebody notices the diff, and
 *  a generated block arriving inside an unrelated change is exactly the diff nobody
 *  reads. So the accepted content of each generated block is pinned in
 *  .github/agent-surface.lock.json, and a change to either one fails this gate
 *  until it is accepted deliberately.
 *
 *  It also answers the second half of the question — whether the generated claim is
 *  still TRUE:
 *
 *    • CLAUDE.md's "N contexts across M groups" must match context-map.json;
 *    • every path context-map.json points at must still exist (blocking, 0 today);
 *    • tracked source files that no context maps is a ratcheted count (159 today).
 *
 *  Runs blocking in CI as part of `npm run check:ci`.
 *
 *  Usage:
 *    node scripts/agent-surface.mjs
 *    node scripts/agent-surface.mjs --check                 # + enforce the ratchet
 *    node scripts/agent-surface.mjs --accept "why it changed"
 *    node scripts/agent-surface.mjs --summary FILE
 */
import { existsSync, readdirSync, readFileSync, writeFileSync, appendFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { dirname, join, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const LOCK_PATH = join(ROOT, ".github", "agent-surface.lock.json");
const MAP_PATH = join(ROOT, "context-map.json");

/** The generated regions, by the markers the generators themselves emit. */
const BLOCKS = [
  {
    id: "AGENTS.md#nextjs-agent-rules",
    file: "AGENTS.md",
    begin: "<!-- BEGIN:nextjs-agent-rules -->",
    end: "<!-- END:nextjs-agent-rules -->",
    owner: "vendor — written and re-added by `next dev`",
  },
  {
    id: "CLAUDE.md#personas:context-map",
    file: "CLAUDE.md",
    begin: "<!-- personas:context-map:start -->",
    end: "<!-- personas:context-map:end -->",
    owner: "tooling — regenerated by the Personas context scan",
  },
];

/** Ratcheted count. Fix findings and lower it in the same commit; never raise it. */
const RATCHET = { unmapped: 159 };

const argv = process.argv.slice(2);
const CHECK = argv.includes("--check");
const acceptIdx = argv.indexOf("--accept");
const ACCEPT = acceptIdx !== -1 ? String(argv[acceptIdx + 1] ?? "").trim() : null;
const dateIdx = argv.indexOf("--date");
const STAMP = dateIdx !== -1 ? String(argv[dateIdx + 1] ?? "").trim() : new Date().toISOString().slice(0, 10);
const summaryIdx = argv.indexOf("--summary");
const SUMMARY_FILE = summaryIdx !== -1 ? argv[summaryIdx + 1] : null;

/** Compare on content, not on whitespace: trailing spaces and blank-line churn
 *  from a generator are noise, a changed sentence is not. */
function normalize(text) {
  return text
    .split(/\r?\n/)
    .map((l) => l.replace(/\s+$/, ""))
    .filter((l) => l !== "");
}

function extract(block) {
  const path = join(ROOT, block.file);
  if (!existsSync(path)) return { error: `${block.file} does not exist` };
  const lines = readFileSync(path, "utf8").split(/\r?\n/);
  const b = lines.findIndex((l) => l.trim() === block.begin);
  const e = lines.findIndex((l) => l.trim() === block.end);
  if (b === -1) return { error: `${block.file}: missing marker ${block.begin}` };
  if (e === -1) return { error: `${block.file}: missing marker ${block.end}` };
  if (e < b) return { error: `${block.file}: ${block.end} appears before ${block.begin}` };
  return { lines: normalize(lines.slice(b + 1, e).join("\n")) };
}

const out = [];
const say = (s = "") => {
  out.push(s);
  console.log(s);
};
const failures = [];

// --- 1. generated blocks vs the lock ----------------------------------------

let lock = { blocks: {} };
if (existsSync(LOCK_PATH)) {
  try {
    lock = JSON.parse(readFileSync(LOCK_PATH, "utf8"));
  } catch (err) {
    console.error(`✗ agent surface: ${LOCK_PATH} is not valid JSON — ${err.message}`);
    process.exit(1);
  }
}

const extracted = new Map();
for (const block of BLOCKS) {
  const res = extract(block);
  if (res.error) {
    failures.push(res.error);
    continue;
  }
  extracted.set(block.id, res.lines);
}

if (ACCEPT !== null) {
  if (ACCEPT.length < 10) {
    console.error('\n✗ --accept needs a reason: --accept "next 16.3.4 reworded the deprecation sentence"\n');
    process.exit(1);
  }
  const blocks = {};
  for (const block of BLOCKS) {
    const lines = extracted.get(block.id);
    if (!lines) continue;
    blocks[block.id] = {
      owner: block.owner,
      acceptedOn: STAMP,
      reason: ACCEPT,
      lines,
    };
  }
  writeFileSync(
    LOCK_PATH,
    JSON.stringify(
      {
        $comment:
          "Accepted content of the parts of the agent instruction surface that are written by tooling, " +
          "not by this team. Compared after normalisation (trailing whitespace and blank lines ignored). " +
          "A mismatch fails `npm run agents:surface`, so a regenerated block has to be read and accepted " +
          "on purpose instead of riding along in an unrelated diff. Accept with: " +
          'npm run agents:surface -- --accept "what changed and why it is fine".',
        blocks,
      },
      null,
      2
    ) + "\n"
  );
  console.log(`✓ accepted ${Object.keys(blocks).length} block(s) into .github/agent-surface.lock.json — commit it.`);
  process.exit(0);
}

say("Agent instruction surface");
say("");

for (const block of BLOCKS) {
  const lines = extracted.get(block.id);
  if (!lines) continue;
  const pinned = lock.blocks?.[block.id];
  if (!pinned) {
    failures.push(`${block.id}: not pinned in .github/agent-surface.lock.json — accept it deliberately.`);
    continue;
  }
  const a = (pinned.lines ?? []).join("\n");
  const b = lines.join("\n");
  if (a === b) {
    say(`  ✓ ${block.id} — unchanged since ${pinned.acceptedOn} (${block.owner})`);
    continue;
  }
  failures.push(`${block.id}: the generated block changed since it was accepted on ${pinned.acceptedOn}.`);
  const pinnedSet = new Set(pinned.lines ?? []);
  const currentSet = new Set(lines);
  for (const l of lines) if (!pinnedSet.has(l)) say(`      + ${l.slice(0, 160)}`);
  for (const l of pinned.lines ?? []) if (!currentSet.has(l)) say(`      - ${l.slice(0, 160)}`);
}

// --- 2. context map: is the generated claim still true? ----------------------

say("");
if (!existsSync(MAP_PATH)) {
  failures.push("context-map.json does not exist, but CLAUDE.md tells every agent to read it.");
} else {
  let map;
  try {
    map = JSON.parse(readFileSync(MAP_PATH, "utf8"));
  } catch (err) {
    failures.push(`context-map.json is not valid JSON — ${err.message}`);
    map = null;
  }

  if (map) {
    const contexts = Array.isArray(map.contexts) ? map.contexts : [];
    const groups = new Set(contexts.map((c) => c.group).filter(Boolean));

    // 2a. CLAUDE.md's stated numbers must match the file it points at.
    const claudeText = existsSync(join(ROOT, "CLAUDE.md")) ? readFileSync(join(ROOT, "CLAUDE.md"), "utf8") : "";
    const claim = /\*\*(\d+) contexts\*\* across \*\*(\d+) groups\*\*/.exec(claudeText);
    if (!claim) {
      say("  • CLAUDE.md states no context/group count (nothing to verify)");
    } else if (Number(claim[1]) !== contexts.length || Number(claim[2]) !== groups.size) {
      failures.push(
        `CLAUDE.md claims ${claim[1]} contexts across ${claim[2]} groups; context-map.json has ` +
          `${contexts.length} across ${groups.size}. The generated summary is describing a scan that no longer matches the map.`
      );
    } else {
      say(`  ✓ CLAUDE.md's claim matches the map: ${contexts.length} contexts across ${groups.size} groups`);
    }

    // 2b. Every path the map points at must exist. A dead reference sends an
    //     agent to a file that is not there, at the moment it is orienting.
    const mapped = new Set();
    (function walk(node) {
      if (typeof node === "string") {
        if (node.startsWith("src/")) mapped.add(node);
      } else if (Array.isArray(node)) {
        for (const v of node) walk(v);
      } else if (node && typeof node === "object") {
        for (const v of Object.values(node)) walk(v);
      }
    })(map);

    const dead = [...mapped].filter((p) => !existsSync(join(ROOT, p))).sort();
    if (dead.length) {
      failures.push(
        `context-map.json points at ${dead.length} path(s) that no longer exist: ${dead.slice(0, 8).join(", ")}` +
          (dead.length > 8 ? ` … and ${dead.length - 8} more` : "")
      );
    } else {
      say(`  ✓ all ${mapped.size} mapped paths exist`);
    }

    // 2c. Coverage — ratcheted, because it does not pass today.
    const tracked = listTrackedSrc();
    const unmapped = tracked.filter((p) => !mapped.has(p));
    const over = unmapped.length > RATCHET.unmapped;
    say(
      `  ${over ? "✗" : "•"} source files no context maps: ${unmapped.length} of ${tracked.length} ` +
        `(baseline ${RATCHET.unmapped})`
    );
    if (unmapped.length) {
      for (const p of unmapped.slice(0, 10)) say(`      ${p}`);
      if (unmapped.length > 10) say(`      … and ${unmapped.length - 10} more`);
    }
    if (over) {
      say("");
      say("  Files were added without being mapped. Re-run the context scan (or edit");
      say("  context-map.json), then lower the baseline in scripts/agent-surface.mjs.");
      if (CHECK) failures.push(`unmapped source files rose to ${unmapped.length} (baseline ${RATCHET.unmapped}).`);
    }

    if (map.generated_at) {
      const days = Math.floor((Date.now() - Date.parse(map.generated_at)) / 86_400_000);
      if (Number.isFinite(days)) say(`  • map last scanned ${days} day(s) ago (${map.generated_at.slice(0, 10)})`);
    }
  }
}

/** Tracked files under src/. git when it is available (a clean checkout in CI, and
 *  it ignores local scratch files); a disk walk otherwise. */
function listTrackedSrc() {
  const git = spawnSync("git", ["ls-files", "src"], { cwd: ROOT, encoding: "utf8" });
  if (git.status === 0 && git.stdout.trim()) {
    return git.stdout.trim().split(/\r?\n/).filter(Boolean);
  }
  const base = join(ROOT, "src");
  if (!existsSync(base)) return [];
  return readdirSync(base, { recursive: true, withFileTypes: true })
    .filter((e) => e.isFile())
    .map((e) => join(e.parentPath ?? e.path, e.name).slice(ROOT.length + 1).split(sep).join("/"));
}

// --- report -----------------------------------------------------------------

if (failures.length) {
  say("");
  say(`✗ ${failures.length} problem(s):`);
  for (const f of failures) say(`  • ${f}`);
  say("");
  say("  A generated block that changed: read it, decide whether the guidance it now");
  say("  gives agents is guidance you want, then accept it on purpose:");
  say('    npm run agents:surface -- --accept "what changed and why it is fine"');
} else {
  say("");
  say("✓ agent surface: generated blocks match what was accepted, and the map's claims still hold.");
}

if (SUMMARY_FILE) {
  try {
    appendFileSync(SUMMARY_FILE, `### Agent instruction surface\n\n\`\`\`\n${out.join("\n")}\n\`\`\`\n`);
  } catch (err) {
    console.error(`(could not write summary: ${err.message})`);
  }
}

process.exit(failures.length ? 1 : 0);
