#!/usr/bin/env node
/** Agent instruction-surface gate (zero-dependency).
 *
 *  Part of the instruction surface agents read is not written by this team:
 *
 *    • AGENTS.md opens with a block that `next dev` writes and RE-ADDS. Delete it
 *      and the next dev server puts it back, so it lands in whatever diff happens
 *      to be open at the time.
 *    • CLAUDE.md's "Project Context Map" section is regenerated by the Personas
 *      context scan and states, as fact, how many contexts exist.
 *
 *  Both are guarded by CODEOWNERS, which is the right instinct and not enough: a
 *  file that regenerates itself is only reviewed if somebody notices the diff, and
 *  a generated block arriving inside an unrelated change is exactly the diff nobody
 *  reads. So the accepted content of each generated block is pinned in
 *  .github/agent-surface.lock.json, and a change to either one fails this gate
 *  until it is accepted deliberately.
 *
 *  It also answers the second half of the question — whether the generated claim is
 *  still TRUE:
 *
 *    • CLAUDE.md's "N contexts across M groups" must match context-map.json;
 *    • every path context-map.json points at must still exist (blocking, 0 today);
 *    • tracked source files that no context maps is a ratcheted count (159 today).
 *
 *  And it answers the question two documents cannot answer about each other: which
 *  one wins. `.ai/manifest.yaml` must declare `guidance.canonical`, it must name a
 *  file that exists, and CLAUDE.md / CONTRIBUTING.md must name that file in prose —
 *  because precedence carried only by an `@AGENTS.md` import is precedence that
 *  only some readers honour, and the one that does not gets a generated context map
 *  and no conventions. The other pointers in that block (the task index, the review
 *  rubric, the required checks, this lock file) must resolve too — `guidance.taskIndex`
 *  is the task → document lookup a run performs before it has read anything, so a
 *  pointer into nothing there is a guess at the worst possible moment.
 *
 *  AND IT READS THE GENERATED TEXT, not only its hash. The lock answers "did this
 *  region change"; it cannot answer "change into WHAT". A generated region is DATA
 *  — a vendor's note that this Next.js differs from your training data, a scan's
 *  count of contexts — and the moment it carries an imperative addressed to the
 *  reader it is guidance nobody on this team wrote, sitting in the file agents
 *  treat as law. So every instruction-shaped line in a generated block is
 *  classified (`scripts/lib/generated-instructions.mjs`) and must already be
 *  present in the accepted lock content: a line the vendor's next rewrite ADDS —
 *  "skip the pre-push check while iterating" — fails this gate, and `--accept`
 *  refuses to pin it without `--accept-instructions` and a human who has read it.
 *  Why generated regions are data rather than instructions:
 *  `docs/adr/0012-generated-regions-are-data.md`.
 *
 *  Runs blocking in CI as part of `npm run check:ci`.
 *
 *  AND THE DRILL. This repository does not trust a fence it has not watched fire
 *  (`npm run lint:fences`, test-unit/contract-ledger-ceiling.test.mjs). `--root`
 *  points this gate at a tree of somebody else's choosing, which is what lets
 *  test-unit/generated-instruction-drill.test.mjs PLANT an instruction inside a
 *  generated block and require a red — including the half that is easiest to lose,
 *  where `--accept` refuses to pin a newly arrived imperative without
 *  `--accept-instructions`. A defence nobody has seen refuse anything is a defence
 *  nobody knows is still connected.
 *
 *  Usage:
 *    node scripts/agent-surface.mjs
 *    node scripts/agent-surface.mjs --check                 # + enforce the ratchet
 *    node scripts/agent-surface.mjs --accept "why it changed"
 *    node scripts/agent-surface.mjs --accept "…" --accept-instructions
 *    node scripts/agent-surface.mjs --summary FILE
 *    node scripts/agent-surface.mjs --root DIR              # run over a fixture tree
 */
import { existsSync, readdirSync, readFileSync, writeFileSync, appendFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { dirname, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { printRemedy } from "./gate-remedy.mjs";
import { directiveLines } from "./lib/generated-instructions.mjs";

const argv = process.argv.slice(2);

/** The tree this gate reads. Overridable so a test can point the REAL gate at a
 *  fixture and require a red — the same override scripts/actions-pin.mjs
 *  (`--permissions`) and scripts/guidance-budget.mjs (`--budget`) carry, for the
 *  same reason: mutating the fixture is the only way to watch a fence fire without
 *  editing the gate that is supposed to be firing. */
const rootIdx = argv.indexOf("--root");
const ROOT =
  rootIdx !== -1 && argv[rootIdx + 1]
    ? resolve(argv[rootIdx + 1])
    : join(dirname(fileURLToPath(import.meta.url)), "..");
const LOCK_PATH = join(ROOT, ".github", "agent-surface.lock.json");
const MAP_PATH = join(ROOT, "context-map.json");

/** The generated regions, by the markers the generators themselves emit. */
const BLOCKS = [
  {
    id: "AGENTS.md#nextjs-agent-rules",
    file: "AGENTS.md",
    begin: "<!-- BEGIN:nextjs-agent-rules -->",
    end: "<!-- END:nextjs-agent-rules -->",
    owner: "vendor — written and re-added by `next dev`",
  },
  {
    id: "CLAUDE.md#personas:context-map",
    file: "CLAUDE.md",
    begin: "<!-- personas:context-map:start -->",
    end: "<!-- personas:context-map:end -->",
    owner: "tooling — regenerated by the Personas context scan",
  },
];

/** Ratcheted count. Fix findings and lower it in the same commit; never raise it. */
const RATCHET = { unmapped: 159 };

const CHECK = argv.includes("--check");
const acceptIdx = argv.indexOf("--accept");
const ACCEPT = acceptIdx !== -1 ? String(argv[acceptIdx + 1] ?? "").trim() : null;
const dateIdx = argv.indexOf("--date");
const STAMP = dateIdx !== -1 ? String(argv[dateIdx + 1] ?? "").trim() : new Date().toISOString().slice(0, 10);
const summaryIdx = argv.indexOf("--summary");
const SUMMARY_FILE = summaryIdx !== -1 ? argv[summaryIdx + 1] : null;
/** Consent for the one thing an acceptance must never be able to do by accident:
 *  pin a NEW instruction, written by a generator, into the file agents obey. */
const ACCEPT_INSTRUCTIONS = argv.includes("--accept-instructions");

/** Compare on content, not on whitespace: trailing spaces and blank-line churn
 *  from a generator are noise, a changed sentence is not. */
function normalize(text) {
  return text
    .split(/\r?\n/)
    .map((l) => l.replace(/\s+$/, ""))
    .filter((l) => l !== "");
}

function extract(block) {
  const path = join(ROOT, block.file);
  if (!existsSync(path)) return { error: `${block.file} does not exist` };
  const lines = readFileSync(path, "utf8").split(/\r?\n/);
  const b = lines.findIndex((l) => l.trim() === block.begin);
  const e = lines.findIndex((l) => l.trim() === block.end);
  if (b === -1) return { error: `${block.file}: missing marker ${block.begin}` };
  if (e === -1) return { error: `${block.file}: missing marker ${block.end}` };
  if (e < b) return { error: `${block.file}: ${block.end} appears before ${block.begin}` };
  return { lines: normalize(lines.slice(b + 1, e).join("\n")) };
}

const out = [];
const say = (s = "") => {
  out.push(s);
  console.log(s);
};
const failures = [];

// --- 1. generated blocks vs the lock ----------------------------------------

let lock = { blocks: {} };
if (existsSync(LOCK_PATH)) {
  try {
    lock = JSON.parse(readFileSync(LOCK_PATH, "utf8"));
  } catch (err) {
    console.error(`✗ agent surface: ${LOCK_PATH} is not valid JSON — ${err.message}`);
    process.exit(1);
  }
}

const extracted = new Map();
for (const block of BLOCKS) {
  const res = extract(block);
  if (res.error) {
    failures.push(res.error);
    continue;
  }
  extracted.set(block.id, res.lines);
}

if (ACCEPT !== null) {
  if (ACCEPT.length < 10) {
    console.error('\n✗ --accept needs a reason: --accept "next 16.3.4 reworded the deprecation sentence"\n');
    process.exit(1);
  }
  // The acceptance is the ONE moment a generator's words become this repository's
  // law, and until now it could not tell the reader which of them were words at
  // all. Any instruction-shaped line that was not already accepted has to be read
  // and consented to by name.
  const arriving = [];
  for (const block of BLOCKS) {
    const lines = extracted.get(block.id);
    if (!lines) continue;
    const alreadyAccepted = new Set(lock.blocks?.[block.id]?.lines ?? []);
    for (const hit of directiveLines(lines)) {
      if (!alreadyAccepted.has(hit.line)) arriving.push({ block: block.id, ...hit });
    }
  }
  if (arriving.length && !ACCEPT_INSTRUCTIONS) {
    console.error(
      `\n✗ ${arriving.length} line(s) in a generated block read as an INSTRUCTION to an agent, and were not in ` +
        "what was accepted before:\n"
    );
    for (const hit of arriving) {
      console.error(`  ${hit.block}\n    ${hit.line.slice(0, 200)}\n    → ${hit.why}\n`);
    }
    console.error(
      "  A generated region is data — a vendor's note, a scan's count — and this repository's guidance is not\n" +
        "  written by a generator (docs/adr/0012-generated-regions-are-data.md). Read each line above and decide\n" +
        "  whether an agent obeying it would do something this team did not ask for. If they are harmless:\n" +
        '    npm run agents:surface -- --accept "…" --accept-instructions\n' +
        "  If one of them is not, do not pin it: the vendor block is regenerated, so the fix is to keep the\n" +
        "  sentence out of the lock and take it to the operator.\n"
    );
    process.exit(1);
  }

  const blocks = {};
  for (const block of BLOCKS) {
    const lines = extracted.get(block.id);
    if (!lines) continue;
    blocks[block.id] = {
      owner: block.owner,
      acceptedOn: STAMP,
      reason: ACCEPT,
      lines,
    };
  }
  writeFileSync(
    LOCK_PATH,
    JSON.stringify(
      {
        $comment:
          "Accepted content of the parts of the agent instruction surface that are written by tooling, " +
          "not by this team. Compared after normalisation (trailing whitespace and blank lines ignored). " +
          "A mismatch fails `npm run agents:surface`, so a regenerated block has to be read and accepted " +
          "on purpose instead of riding along in an unrelated diff. Accept with: " +
          'npm run agents:surface -- --accept "what changed and why it is fine". These regions carry DATA; ' +
          "a line in one that reads as an instruction to an agent has to be consented to by name with " +
          "--accept-instructions (docs/adr/0012-generated-regions-are-data.md).",
        blocks,
      },
      null,
      2
    ) + "\n"
  );
  console.log(`✓ accepted ${Object.keys(blocks).length} block(s) into .github/agent-surface.lock.json — commit it.`);
  process.exit(0);
}

say("Agent instruction surface");
say("");

for (const block of BLOCKS) {
  const lines = extracted.get(block.id);
  if (!lines) continue;
  const pinned = lock.blocks?.[block.id];
  if (!pinned) {
    failures.push(`${block.id}: not pinned in .github/agent-surface.lock.json — accept it deliberately.`);
    continue;
  }
  const a = (pinned.lines ?? []).join("\n");
  const b = lines.join("\n");
  if (a === b) {
    say(`  ✓ ${block.id} — unchanged since ${pinned.acceptedOn} (${block.owner})`);
    continue;
  }
  failures.push(`${block.id}: the generated block changed since it was accepted on ${pinned.acceptedOn}.`);
  const pinnedSet = new Set(pinned.lines ?? []);
  const currentSet = new Set(lines);
  for (const l of lines) if (!pinnedSet.has(l)) say(`      + ${l.slice(0, 160)}`);
  for (const l of pinned.lines ?? []) if (!currentSet.has(l)) say(`      - ${l.slice(0, 160)}`);
}

// --- 1b. generated regions are DATA, not instructions ------------------------
//
// The lock above compares content and cannot read it. This does: every line in a
// generated block that reads as an imperative addressed to an agent has to be one
// a human already accepted, by name, in the lock file. A vendor rewrite that adds
// "skip the pre-push check while iterating" therefore cannot become guidance by
// riding through an acceptance nobody looked at — it is listed here, and again at
// `--accept`, where consent is a separate flag.

for (const block of BLOCKS) {
  const lines = extracted.get(block.id);
  if (!lines) continue;
  const accepted = new Set(lock.blocks?.[block.id]?.lines ?? []);
  const hits = directiveLines(lines);
  const unaccepted = hits.filter((h) => !accepted.has(h.line));
  if (unaccepted.length) {
    failures.push(
      `${block.id}: ${unaccepted.length} line(s) read as an instruction to an agent and are not in the accepted ` +
        "content. A generated region is data, not guidance (docs/adr/0012-generated-regions-are-data.md)."
    );
    for (const hit of unaccepted) {
      say(`      ! ${hit.line.slice(0, 160)}`);
      say(`        ${hit.why}`);
    }
  } else if (hits.length) {
    say(
      `  ✓ ${block.id} — ${hits.length} instruction-shaped line(s), each one already read and accepted ` +
        "(generated text is data; the guidance is AGENTS.md)"
    );
  }
}

// --- 2. context map: is the generated claim still true? ----------------------

say("");
if (!existsSync(MAP_PATH)) {
  failures.push("context-map.json does not exist, but CLAUDE.md tells every agent to read it.");
} else {
  let map;
  try {
    map = JSON.parse(readFileSync(MAP_PATH, "utf8"));
  } catch (err) {
    failures.push(`context-map.json is not valid JSON — ${err.message}`);
    map = null;
  }

  if (map) {
    const contexts = Array.isArray(map.contexts) ? map.contexts : [];
    const groups = new Set(contexts.map((c) => c.group).filter(Boolean));

    // 2a. CLAUDE.md's stated numbers must match the file it points at.
    const claudeText = existsSync(join(ROOT, "CLAUDE.md")) ? readFileSync(join(ROOT, "CLAUDE.md"), "utf8") : "";
    const claim = /\*\*(\d+) contexts\*\* across \*\*(\d+) groups\*\*/.exec(claudeText);
    if (!claim) {
      say("  • CLAUDE.md states no context/group count (nothing to verify)");
    } else if (Number(claim[1]) !== contexts.length || Number(claim[2]) !== groups.size) {
      failures.push(
        `CLAUDE.md claims ${claim[1]} contexts across ${claim[2]} groups; context-map.json has ` +
          `${contexts.length} across ${groups.size}. The generated summary is describing a scan that no longer matches the map.`
      );
    } else {
      say(`  ✓ CLAUDE.md's claim matches the map: ${contexts.length} contexts across ${groups.size} groups`);
    }

    // 2b. Every path the map points at must exist. A dead reference sends an
    //     agent to a file that is not there, at the moment it is orienting.
    const mapped = new Set();
    (function walk(node) {
      if (typeof node === "string") {
        if (node.startsWith("src/")) mapped.add(node);
      } else if (Array.isArray(node)) {
        for (const v of node) walk(v);
      } else if (node && typeof node === "object") {
        for (const v of Object.values(node)) walk(v);
      }
    })(map);

    const dead = [...mapped].filter((p) => !existsSync(join(ROOT, p))).sort();
    if (dead.length) {
      failures.push(
        `context-map.json points at ${dead.length} path(s) that no longer exist: ${dead.slice(0, 8).join(", ")}` +
          (dead.length > 8 ? ` … and ${dead.length - 8} more` : "")
      );
    } else {
      say(`  ✓ all ${mapped.size} mapped paths exist`);
    }

    // 2c. Coverage — ratcheted, because it does not pass today.
    const tracked = listTrackedSrc();
    const unmapped = tracked.filter((p) => !mapped.has(p));
    const over = unmapped.length > RATCHET.unmapped;
    say(
      `  ${over ? "✗" : "•"} source files no context maps: ${unmapped.length} of ${tracked.length} ` +
        `(baseline ${RATCHET.unmapped})`
    );
    if (unmapped.length) {
      for (const p of unmapped.slice(0, 10)) say(`      ${p}`);
      if (unmapped.length > 10) say(`      … and ${unmapped.length - 10} more`);
    }
    if (over) {
      say("");
      say("  Files were added without being mapped. Re-run the context scan (or edit");
      say("  context-map.json), then lower the baseline in scripts/agent-surface.mjs.");
      if (CHECK) failures.push(`unmapped source files rose to ${unmapped.length} (baseline ${RATCHET.unmapped}).`);
    }

    if (map.generated_at) {
      const days = Math.floor((Date.now() - Date.parse(map.generated_at)) / 86_400_000);
      if (Number.isFinite(days)) say(`  • map last scanned ${days} day(s) ago (${map.generated_at.slice(0, 10)})`);
    }
  }
}

// --- 3. is a canonical guidance document nominated, and does it hold? --------
//
// Two documents that agree today are still two documents, and an agent that
// resolves `@` imports reads them in a different order from one that does not.
// `.ai/manifest.yaml` is the file designed to answer "which do I trust first", so
// the answer has to be IN it, has to name a file that exists, and the entry-point
// document has to point at the same place in prose — otherwise a reader without
// import support gets a generated map and no conventions, with nothing telling it
// what it missed.

say("");
{
  const manifestPath = join(ROOT, ".ai", "manifest.yaml");
  if (!existsSync(manifestPath)) {
    failures.push(".ai/manifest.yaml does not exist, so nothing declares which guidance document is canonical.");
  } else {
    const lines = readFileSync(manifestPath, "utf8").split(/\r?\n/);
    const start = lines.findIndex((l) => /^guidance\s*:/.test(l));
    if (start === -1) {
      failures.push(
        ".ai/manifest.yaml declares no `guidance:` block — add `guidance.canonical` naming the document that wins " +
          "when two disagree. Precedence that lives only in an `@` import is precedence only some readers honour."
      );
    } else {
      const body = [];
      for (let i = start + 1; i < lines.length; i++) {
        const l = lines[i];
        if (l.trim() !== "" && !l.startsWith(" ")) break;
        body.push(l);
      }
      const scalar = (key) => {
        const hit = body.find((l) => new RegExp(`^\\s{2}${key}\\s*:`).test(l));
        if (!hit) return null;
        const v = hit.slice(hit.indexOf(":") + 1).trim();
        return v.replace(/^["']|["']$/g, "") || null;
      };

      const canonical = scalar("canonical");
      if (!canonical) {
        failures.push(".ai/manifest.yaml has a `guidance:` block but no `canonical:` — name the document that wins.");
      } else if (!existsSync(join(ROOT, canonical))) {
        failures.push(`.ai/manifest.yaml nominates \`${canonical}\` as canonical guidance, but that file does not exist.`);
      } else {
        // The entry-point files must say so too, in prose a reader that does not
        // resolve imports still sees.
        const silent = ["CLAUDE.md", "CONTRIBUTING.md"]
          .filter((f) => f !== canonical && existsSync(join(ROOT, f)))
          .filter((f) => !readFileSync(join(ROOT, f), "utf8").includes(canonical));
        if (silent.length) {
          failures.push(
            `${silent.join(" and ")} never mention${silent.length === 1 ? "s" : ""} ${canonical}, which ` +
              ".ai/manifest.yaml nominates as canonical. A reader that opens only that file learns nothing about it."
          );
        } else {
          say(`  ✓ canonical guidance: ${canonical} — nominated in .ai/manifest.yaml and named in the entry points`);
        }
      }

      // The other pointers in the block are only useful if they resolve.
      for (const key of ["taskIndex", "review", "requiredChecks", "surfaceLock"]) {
        const value = scalar(key);
        if (!value) continue;
        if (existsSync(join(ROOT, value))) say(`  ✓ guidance.${key} → ${value}`);
        else failures.push(`.ai/manifest.yaml guidance.${key} points at \`${value}\`, which does not exist.`);
      }
    }
  }
}

/** Tracked files under src/. git when it is available (a clean checkout in CI, and
 *  it ignores local scratch files); a disk walk otherwise. */
function listTrackedSrc() {
  const git = spawnSync("git", ["ls-files", "src"], { cwd: ROOT, encoding: "utf8" });
  if (git.status === 0 && git.stdout.trim()) {
    return git.stdout.trim().split(/\r?\n/).filter(Boolean);
  }
  const base = join(ROOT, "src");
  if (!existsSync(base)) return [];
  return readdirSync(base, { recursive: true, withFileTypes: true })
    .filter((e) => e.isFile())
    .map((e) => join(e.parentPath ?? e.path, e.name).slice(ROOT.length + 1).split(sep).join("/"));
}

// --- report -----------------------------------------------------------------

if (failures.length) {
  say("");
  say(`✗ ${failures.length} problem(s):`);
  for (const f of failures) say(`  • ${f}`);
  say("");
  printRemedy("agents:surface", say);
} else {
  say("");
  say("✓ agent surface: generated blocks match what was accepted, and the map's claims still hold.");
}

if (SUMMARY_FILE) {
  try {
    appendFileSync(SUMMARY_FILE, `### Agent instruction surface\n\n\`\`\`\n${out.join("\n")}\n\`\`\`\n`);
  } catch (err) {
    console.error(`(could not write summary: ${err.message})`);
  }
}

process.exit(failures.length ? 1 : 0);
