#!/usr/bin/env node
/** Does context-map.json still describe the code? (zero-dependency, no network.)
 *
 *  CLAUDE.md tells every agent to read `context-map.json` at task start and scope
 *  its edits to the relevant context's `file_paths`. That map is GENERATED by the
 *  Personas context scan, and until now everything that checked it checked its
 *  bookkeeping rather than its truth: `npm run agents:surface` proves the counts in
 *  CLAUDE.md match the map, that every mapped path still exists, and how many
 *  source files no context maps. None of that notices the thing that actually
 *  rots — a module in one feature group reaching into another, until the group
 *  boundaries are a description of history rather than a constraint on where the
 *  next file goes.
 *
 *  This reads the boundary the map declares and the import graph the code actually
 *  has, and puts them next to each other.
 *
 *  WHAT COUNTS AS A CROSSING. An import from a file in context C to a file in
 *  context D, where C and D sit in different GROUPS, and C does not name D in its
 *  `cross_refs`. Three deliberate exemptions, because a rule that fires on healthy
 *  code gets switched off:
 *
 *    • groups whose domain is `shared` or `infrastructure` (App Shell & Site,
 *      Platform Operations) may be imported by anybody without a declaration. That
 *      is what a shared group IS — the AppShell, the design system, the store
 *      seams. Coupling INTO them is the architecture working;
 *    • a target file no context maps is skipped. 159 tracked source files are
 *      unmapped (agents:surface owns that number) and a boundary claim about a file
 *      the map has never seen would be an invention;
 *    • an edge the importing context DECLARES in `cross_refs` is fine. That is the
 *      map being used as a constraint: crossing deliberately means writing the
 *      crossing down, in a diff a reviewer reads.
 *
 *  Rung discipline (docs/adr/0007-gate-rung-discipline.md). This is two halves and
 *  they sit on different rungs on purpose:
 *
 *    BLOCKING (`--check`, inside check:ci) — the DIFF. For every changed, mapped
 *      TypeScript file, the undeclared cross-group imports it has now are compared
 *      with the ones it had at the merge base. A crossing it did not have before
 *      fails the build. This passes on the tree today by construction: an empty
 *      diff has no new crossings, and it can only ever fire on a boundary THIS
 *      change crossed.
 *
 *    REPORTING (default) — the CENSUS over the whole tree. It prints today's
 *      undeclared crossings, grouped by the pair of groups they connect, and exits
 *      0. It carries no ratchet baseline, and that is a considered position rather
 *      than the third rung ADR-0007 bans: a ratchet exists to notice a rise, and
 *      the blocking half above already refuses every rise at the commit that
 *      introduces it. A baseline here would be a second, weaker copy of a rule that
 *      already holds. What the census is for is the other question — whether the 16
 *      groups are boundaries worth defending or names for what happens to be there
 *      — and that is a reading, not an exit code.
 *
 *  THE FIX, when it fires, is one of three and the message says so: import through
 *  a shared context instead; move the file to the context it actually belongs to
 *  (and rescan); or declare the crossing in the importing context's `cross_refs`.
 *  The third is legitimate and cheap — it is a line of JSON — which is the point:
 *  the map stops being a description and becomes the place a boundary decision is
 *  recorded.
 *
 *  Usage:
 *    node scripts/context-decay.mjs                  # census over the whole tree
 *    node scripts/context-decay.mjs --check          # fail on a NEW crossing in the diff
 *    node scripts/context-decay.mjs --check --base <ref>
 *    node scripts/context-decay.mjs --summary FILE
 */
import { appendFileSync, existsSync, readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const MAP_PATH = join(ROOT, "context-map.json");

const argv = process.argv.slice(2);
const CHECK = argv.includes("--check");
const arg = (name) => {
  const i = argv.indexOf(name);
  return i !== -1 ? argv[i + 1] : null;
};
const SUMMARY_FILE = arg("--summary");

/** Group domains that anybody may import without declaring it — see the header. */
const OPEN_DOMAINS = new Set(["shared", "infrastructure"]);

const out = [];
const say = (s = "") => {
  out.push(s);
  console.log(s);
};

/** Write the job summary (when asked) and leave with a code — used by both halves,
 *  so a `--check` run reports into the same place the census does. */
function finish(code) {
  if (SUMMARY_FILE) {
    try {
      appendFileSync(SUMMARY_FILE, `### Context map decay\n\n\`\`\`\n${out.join("\n")}\n\`\`\`\n`);
    } catch (err) {
      console.error(`(could not write summary: ${err.message})`);
    }
  }
  process.exit(code);
}

if (!existsSync(MAP_PATH)) {
  console.error("✗ context decay: context-map.json does not exist, but CLAUDE.md tells every agent to read it.");
  process.exit(1);
}

let map;
try {
  map = JSON.parse(readFileSync(MAP_PATH, "utf8"));
} catch (err) {
  console.error(`✗ context decay: context-map.json is not valid JSON — ${err.message}`);
  process.exit(1);
}

const contexts = Array.isArray(map.contexts) ? map.contexts : [];
const groupDomain = new Map(
  (Array.isArray(map.groups) ? map.groups : []).map((g) => [g.name, String(g.domain ?? "")])
);

/** repo-relative path (forward slashes) → the context that claims it. A file claimed
 *  by two contexts keeps the first; the boundary question is the same either way. */
const owner = new Map();
for (const ctx of contexts) {
  for (const p of Array.isArray(ctx.file_paths) ? ctx.file_paths : []) {
    const key = String(p).replace(/\\/g, "/");
    if (!owner.has(key)) owner.set(key, ctx);
  }
}

const declared = new Map(
  contexts.map((c) => [c.name, new Set((Array.isArray(c.cross_refs) ? c.cross_refs : []).map(String))])
);

/** Every module specifier a source text imports from, in the three spellings this
 *  codebase uses: `from "…"`, a bare side-effect `import "…"`, and `import("…")`. */
function specifiers(text) {
  const found = new Set();
  for (const re of [
    /\bfrom\s*["']([^"']+)["']/g,
    /\bimport\s+["']([^"']+)["']/g,
    /\bimport\s*\(\s*["']([^"']+)["']\s*\)/g,
  ]) {
    for (const m of text.matchAll(re)) found.add(m[1]);
  }
  return [...found];
}

const EXTS = ["", ".ts", ".tsx", ".mts", ".js", ".jsx", "/index.ts", "/index.tsx"];

/** Resolve a specifier written in `fromFile` to a repo-relative path the map knows
 *  about, or null. Only `@/…` (tsconfig paths → src/) and relative specifiers can
 *  reach another context; a bare package name cannot. */
function resolve(spec, fromFile) {
  let base;
  if (spec.startsWith("@/")) base = `src/${spec.slice(2)}`;
  else if (spec.startsWith("./") || spec.startsWith("../")) {
    const parts = `${fromFile.split("/").slice(0, -1).join("/")}/${spec}`.split("/");
    const stack = [];
    for (const part of parts) {
      if (part === "." || part === "") continue;
      if (part === "..") stack.pop();
      else stack.push(part);
    }
    base = stack.join("/");
  } else return null;

  for (const ext of EXTS) {
    const candidate = `${base}${ext}`;
    if (owner.has(candidate)) return candidate;
  }
  return null;
}

/** The undeclared cross-group edges a file's text introduces, as `context name`s. */
function crossings(file, text) {
  const from = owner.get(file);
  if (!from) return [];
  const fromDeclared = declared.get(from.name) ?? new Set();
  const hits = new Map();
  for (const spec of specifiers(text)) {
    const target = resolve(spec, file);
    if (!target) continue;
    const to = owner.get(target);
    if (!to || to.name === from.name) continue;
    if (to.group === from.group) continue;
    if (OPEN_DOMAINS.has(groupDomain.get(to.group) ?? "")) continue;
    if (fromDeclared.has(to.name)) continue;
    if (!hits.has(to.name)) hits.set(to.name, { context: to.name, group: to.group, spec, target });
  }
  return [...hits.values()];
}

const read = (p) => {
  try {
    return readFileSync(join(ROOT, ...p.split("/")), "utf8");
  } catch {
    return null;
  }
};

const isSource = (p) => /\.(ts|tsx|mts)$/.test(p) && !p.endsWith(".d.ts");

// --- blocking half: a NEW crossing in this change ----------------------------

if (CHECK) {
  const git = (args) => {
    const res = spawnSync("git", args, { cwd: ROOT, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
    return res.status === 0 ? res.stdout : null;
  };
  const base = [arg("--base"), process.env.AGENT_REVIEW_BASE, "origin/master", "master", "HEAD~1"]
    .filter(Boolean)
    .find((c) => git(["rev-parse", "--verify", "--quiet", `${c}^{commit}`]));

  if (!base) {
    say("context decay: no base revision to diff against — nothing to check.");
    finish(0);
  }

  const nameStatus = (git(["diff", "--name-status", `${base}...HEAD`]) ?? "").trim();
  if (!nameStatus) {
    say(`context decay: no changes against ${base} — nothing to check.`);
    finish(0);
  }

  const changed = nameStatus
    .split(/\r?\n/)
    .map((line) => line.split("\t"))
    .filter((parts) => parts[0] && parts[0][0] !== "D")
    .map((parts) => parts[parts.length - 1].replace(/\\/g, "/"))
    .filter((p) => isSource(p) && owner.has(p));

  const violations = [];
  for (const file of changed) {
    const now = read(file);
    if (now === null) continue;
    const before = git(["show", `${base}:${file}`]);
    const had = new Set(before === null ? [] : crossings(file, before).map((c) => c.context));
    for (const c of crossings(file, now)) {
      if (had.has(c.context)) continue; // inherited, not introduced here
      const from = owner.get(file);
      violations.push(
        `${file} (context "${from.name}", group "${from.group}") now imports ${c.spec} → ` +
          `${c.target} (context "${c.context}", group "${c.group}"). That crossing is new in this change ` +
          "and the map does not declare it. Import through a shared context, move the file to the context " +
          `it belongs to, or add "${c.context}" to "${from.name}".cross_refs in context-map.json.`
      );
    }
  }

  say(
    `context decay: ${changed.length} changed mapped source file(s) against ${base} — ` +
      `${violations.length} new cross-group import(s).`
  );
  if (violations.length) {
    say("");
    say(`✗ ${violations.length} undeclared boundary crossing(s) introduced by this change:`);
    for (const v of violations) say(`  • ${v}`);
    finish(1);
  }
  say("✓ no feature group started reaching into another one in this change.");
  finish(0);
}

// --- reporting half: the census ----------------------------------------------

const pairs = new Map();
let scanned = 0;
let total = 0;
for (const [file] of owner) {
  if (!isSource(file)) continue;
  const text = read(file);
  if (text === null) continue;
  scanned++;
  for (const c of crossings(file, text)) {
    const from = owner.get(file);
    const key = `${from.group} → ${c.group}`;
    if (!pairs.has(key)) pairs.set(key, []);
    pairs.get(key).push(`${file} → ${c.target}`);
    total++;
  }
}

say(`Context map decay — ${contexts.length} contexts, ${groupDomain.size} groups, ${scanned} mapped source files`);
say("");
say(`  undeclared cross-group imports: ${total}`);
say("");
for (const [pair, edges] of [...pairs.entries()].sort((a, b) => b[1].length - a[1].length)) {
  say(`  ${String(edges.length).padStart(4)}  ${pair}`);
  for (const e of edges.slice(0, 3)) say(`        ${e}`);
  if (edges.length > 3) say(`        … and ${edges.length - 3} more`);
}
say("");
say(
  total === 0
    ? "  Every import either stays inside its group, targets a shared/infrastructure group, or is declared."
    : "  These are inherited, not introduced: `--check` fails a change that adds one, so this number can " +
        "only go down. Each line is either a boundary to defend (fix the import) or a boundary that is not " +
        "real (declare it in cross_refs, or merge the groups on the next scan)."
);

finish(0);
