#!/usr/bin/env node
/** Quality floor for the baked LLM scorecard (zero-dependency, no model calls).
 *
 *  `npm run llm:quality` is a benchmark: it spends real tokens, takes ~30 minutes,
 *  and has no assertions — it tells you which model writes the best output per
 *  operation. Nothing about that can run on a pull request. What CAN run on every
 *  pull request is a check over the result it BAKES into the app
 *  (src/lib/llm/quality-scores.ts), because that file is committed data and the
 *  same scores are the public surface at /kvalita-modelu.
 *
 *  That is the split this gate implements: the expensive judged run stays on
 *  demand, and the number it produces acquires a threshold.
 *
 *  Runs blocking in CI as part of `npm run check:ci`. Exit non-zero fails it.
 *
 *    BLOCKING — passes on the tree today (docs/adr/0007-gate-rung-discipline.md):
 *      • every operation the app SERVES scores at or above the floor;
 *      • no serving-model cell is marked invalid — a `valid: false` cell means the
 *        model's output failed that tool's own validator, i.e. production would
 *        have clamped or dropped it;
 *      • the scorecard actually contains the models the app serves with.
 *
 *    REPORTING, ratcheted — does NOT pass today, so it prints and exits 0 unless a
 *    count rises above the baseline below:
 *      • operations in the tool registry with no baked score at all;
 *      • baked operations that no longer exist in the registry (a retired tool
 *        still shown on the public scorecard);
 *      • how old the measurement is.
 *
 *  Usage:
 *    node scripts/quality-gate.mjs            # report + enforce the floor
 *    node scripts/quality-gate.mjs --check    # same, and enforce the ratchet too
 *    node scripts/quality-gate.mjs --summary FILE
 */
import { appendFileSync, existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SCORES = join(ROOT, "src", "lib", "llm", "quality-scores.ts");
const GOLDEN_DIR = join(ROOT, "test-llm", "golden");

/** The models the app actually serves with, and therefore the only columns whose
 *  score is a statement about what a user receives. Dev and the BYOM Anthropic
 *  default resolve to Claude Sonnet; production and the BYOM Gemini default
 *  resolve to Gemini Flash (src/lib/llm/index.ts, src/lib/llm/models.ts). The
 *  other columns in the scorecard are the comparison field — they inform BYOM
 *  recommendations and are deliberately NOT gated. */
const SERVING_MODELS = ["anthropic/claude-sonnet-5", "google/gemini-3.5-flash"];

/** Below this, the judge is not splitting hairs — at 6 and under its written
 *  issues are things like inventing figures the grounding block does not contain.
 *  Both serving columns sit at 7.0 or above on every baked operation today, so
 *  6.5 leaves one half-point of run-to-run variance and still fails a real drop.
 *  Raising it is a decision to make after a fresh full matrix, not a nudge. */
const FLOOR = 6.5;

/** Reporting-rung ratchet. Fix findings and lower these in the same commit;
 *  never raise them. Measured 2026-08-26 against the 2026-07-07 bake. */
const RATCHET = {
  /** registry tools with no baked score: ads-diagnosis, channel-research,
   *  local-diagnosis, monthly-recap, onboarding-scan, twin-reply, twin-style —
   *  plus `local-page` (W2-C, 2026-08-29), the same +1 ads-diagnosis took in
   *  Wave 1: a tool lands with its contract golden, and its quality cells are
   *  measured on the next full `npm run llm:quality` bake. Lower this back to 6
   *  when both are baked; never raise it for anything else. */
  unbaked: 8,
  /** baked operations no longer in the registry: lead-reply (retired when the
   *  twin absorbed it). It is still on the public scorecard. */
  retired: 1,
};

const argv = process.argv.slice(2);
const CHECK = argv.includes("--check");
const summaryIdx = argv.indexOf("--summary");
const SUMMARY_FILE = summaryIdx !== -1 ? argv[summaryIdx + 1] : null;

// --- parse the baked scorecard ----------------------------------------------
// It is generated by scripts/bake-quality-scores.mjs as
// `export const QUALITY_SCORES: QualityScores = <JSON.stringify(data, null, 2)>;`
// so the object is exactly the text from the first `{` to the `};` at column 0.

if (!existsSync(SCORES)) {
  console.error(`✗ quality gate: ${SCORES} is missing.`);
  process.exit(1);
}

const raw = readFileSync(SCORES, "utf8");
const open = raw.indexOf("{", raw.indexOf("export const QUALITY_SCORES"));
const close = raw.indexOf("\n};", open);
if (open === -1 || close === -1) {
  console.error("✗ quality gate: could not find the QUALITY_SCORES object literal — was the generator changed?");
  process.exit(1);
}

let data;
try {
  data = JSON.parse(raw.slice(open, close + 2));
} catch (err) {
  console.error(`✗ quality gate: the baked scorecard is not parseable JSON — ${err.message}`);
  process.exit(1);
}

const cells = data.cells ?? {};
const models = data.models ?? [];
const operations = Object.keys(cells).sort();

const goldenIds = existsSync(GOLDEN_DIR)
  ? readdirSync(GOLDEN_DIR)
      .filter((f) => f.endsWith(".json"))
      .map((f) => f.replace(/\.json$/, ""))
  : [];

// --- checks -----------------------------------------------------------------

const out = [];
const say = (s = "") => {
  out.push(s);
  console.log(s);
};

const blocking = [];

if (operations.length === 0) {
  blocking.push("the scorecard is empty — no matrix run has been baked in.");
}

for (const model of SERVING_MODELS) {
  if (!models.includes(model)) {
    blocking.push(
      `${model} is a model the app serves with, but the scorecard has no column for it. ` +
        "Either it stopped serving (update SERVING_MODELS in scripts/quality-gate.mjs) " +
        "or the last matrix run did not include it (re-run with it in LLM_QUALITY_TARGETS)."
    );
  }
}

const floorRows = [];
for (const op of operations) {
  for (const model of SERVING_MODELS) {
    const cell = cells[op]?.[model];
    if (!cell) continue; // absence is a coverage finding, below — not a floor failure
    floorRows.push({ op, model, score: cell.score, valid: cell.valid });
    if (typeof cell.score !== "number") {
      blocking.push(`${op} × ${model}: no score recorded.`);
    } else if (cell.score < FLOOR) {
      blocking.push(`${op} × ${model}: scored ${cell.score}, below the ${FLOOR} floor.`);
    }
    if (cell.valid === false) {
      blocking.push(
        `${op} × ${model}: the judged output FAILED the tool's own validator (valid: false) — ` +
          "production would clamp or drop it."
      );
    }
  }
}

const unbaked = goldenIds.filter((id) => !operations.includes(id)).sort();
const retired = operations.filter((op) => !goldenIds.includes(op)).sort();

// --- report -----------------------------------------------------------------

say(`LLM quality gate — floor ${FLOOR}, serving models: ${SERVING_MODELS.join(", ")}`);
say(`  baked ${operations.length} operation(s) × ${models.length} model(s), measured ${data.measuredAt || "(unknown)"}, judge ${data.judge || "(unknown)"}`);
say("");

if (floorRows.length) {
  const worst = [...floorRows].sort((a, b) => (a.score ?? 0) - (b.score ?? 0)).slice(0, 5);
  say("  lowest serving-model cells:");
  for (const r of worst) say(`    ${String(r.score).padEnd(5)} ${r.op} × ${r.model}${r.valid === false ? "  ⚠ invalid" : ""}`);
  say("");
}

if (data.measuredAt) {
  const days = Math.floor((Date.now() - Date.parse(data.measuredAt)) / 86_400_000);
  if (Number.isFinite(days)) {
    say(`  measurement age: ${days} day(s)${days > 120 ? " — stale enough that the numbers describe a model line-up that has moved on" : ""}`);
    say("");
  }
}

let ratchetBroken = false;
const ratchetLine = (label, found, baseline, detail) => {
  const over = found > baseline;
  if (over) ratchetBroken = true;
  say(`  ${over ? "✗" : "•"} ${label}: ${found} (baseline ${baseline})${detail ? ` — ${detail}` : ""}`);
};

ratchetLine("registry tools with no baked score", unbaked.length, RATCHET.unbaked, unbaked.join(", ") || "none");
ratchetLine("baked operations no longer in the registry", retired.length, RATCHET.retired, retired.join(", ") || "none");

if (ratchetBroken) {
  say("");
  say("  A ratchet count rose. Bake the missing operations (`npm run llm:quality` then");
  say("  `npm run llm:quality:bake`) or lower the baseline in scripts/quality-gate.mjs.");
  say("  Never raise a baseline.");
}

if (blocking.length) {
  say("");
  say(`✗ ${blocking.length} quality floor failure(s):`);
  for (const b of blocking) say(`  • ${b}`);
  say("");
  say("  These are not advisory. A serving model below the floor, or producing output");
  say("  its own validator rejects, is a product defect on a surface users read.");
} else {
  say("");
  say("✓ every serving-model cell is at or above the floor and passes its tool's validator.");
}

if (SUMMARY_FILE) {
  try {
    appendFileSync(SUMMARY_FILE, `### LLM quality gate\n\n\`\`\`\n${out.join("\n")}\n\`\`\`\n`);
  } catch (err) {
    console.error(`(could not write summary: ${err.message})`);
  }
}

if (blocking.length) process.exit(1);
if (CHECK && ratchetBroken) process.exit(1);
