/** Bilingual copy for the winning-patterns library. Lifted out of the component
 *  so PatternsLibrary stays editable without growing (AGENTS.md 200-LOC rubric;
 *  same shape as modules/leads/copy.ts and profit/strings.ts). Plain data — the
 *  component still owns it, it just is not 76 lines in the middle of it. */
export const PATTERNS_T = {
  cs: {
    infoBanner: "Vzory se odvozují z vašich vlastních výsledků. Hledání je",
    infoBannerSemantic: "sémantické",
    infoBannerSuffix: "a najde vzory podle významu, ne jen podle slov. Uložené vzory navíc ladí AI vyhodnocení portfolia.",
    filterAll: "Vše",
    searchPlaceholder: "Hledat podle významu…",
    searchAriaLabel: "Hledat",
    clearSearch: "Vymazat",
    loading: "Načítám vzory…",
    searchResults: "Výsledky hledání ({n})",
    searching: "Hledám…",
    semantic: "Sémantické",
    textual: "Textové",
    noResults: "Nic neodpovídá dotazu.",
    yourLibrary: "Vaše knihovna ({n})",
    emptyLibrary: "Zatím nemáte nic uloženo. Připněte si rozpoznané vzory níže nebo přidejte vlastní.",
    noFilterMatch: "Žádný uložený vzor neodpovídá filtru.",
    autoDetected: "Automaticky rozpoznané z dat ({n})",
    noData: "Zatím nejsou data k analýze. Synchronizujte kampaně na stránce Kampaně.",
    libraryUnavailable:
      "Knihovnu se teď nepodařilo načíst, takže nevíme, jestli nějaké vzory existují. Zkuste to prosím znovu později.",
    noAutoFilterMatch: "Žádný rozpoznaný vzor neodpovídá filtru.",
    relevanceTitle: "Relevance k dotazu",
    relevanceLabel: "relevance",
    contradictedLabel: "Již neodpovídá datům",
    contradictedTitle: "Čerstvě vytěžená data odporují tomuto uloženému vzoru. Zvažte jeho odebrání.",
    savedAgePrefix: "Uloženo",
    removeLabel: "Odebrat",
    saveLabel: "Uložit",
    addCustomTitle: "Přidat vlastní vzor",
    patternNamePlaceholder: "Název vzoru",
    insightPlaceholder: "Poučení / pravidlo",
    evidencePlaceholder: "Důkaz / čísla (volitelné)",
    saveBusy: "Ukládám…",
    saveBtn: "Uložit vzor",
    saveFailed: "Uložení se nezdařilo.",
  },
  en: {
    infoBanner: "Patterns are derived from your own results. Search is",
    infoBannerSemantic: "semantic",
    infoBannerSuffix: "and finds patterns by meaning, not just keywords. Saved patterns also tune the AI portfolio evaluation.",
    filterAll: "All",
    searchPlaceholder: "Search by meaning…",
    searchAriaLabel: "Search",
    clearSearch: "Clear",
    loading: "Loading patterns…",
    searchResults: "Search results ({n})",
    searching: "Searching…",
    semantic: "Semantic",
    textual: "Text",
    noResults: "Nothing matches your query.",
    yourLibrary: "Your library ({n})",
    emptyLibrary: "Nothing saved yet. Pin detected patterns below or add your own.",
    noFilterMatch: "No saved pattern matches the filter.",
    autoDetected: "Auto-detected from data ({n})",
    noData: "No data to analyze yet. Sync campaigns on the Campaigns page.",
    libraryUnavailable:
      "The library could not be loaded just now, so we cannot tell whether any patterns exist. Please try again later.",
    noAutoFilterMatch: "No detected pattern matches the filter.",
    relevanceTitle: "Relevance to query",
    relevanceLabel: "relevance",
    contradictedLabel: "No longer matches the data",
    contradictedTitle: "Freshly mined data contradicts this saved pattern. Consider removing it.",
    savedAgePrefix: "Saved",
    removeLabel: "Remove",
    saveLabel: "Save",
    addCustomTitle: "Add custom pattern",
    patternNamePlaceholder: "Pattern name",
    insightPlaceholder: "Insight / rule",
    evidencePlaceholder: "Evidence / numbers (optional)",
    saveBusy: "Saving…",
    saveBtn: "Save pattern",
    saveFailed: "Save failed.",
  },
} as const;
